### ISSUE TITLE
资金-其他收入单/其他支出单选择多个类别或者收支项，贷方生成一条凭证行

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1010]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

![image](https://cloud.githubusercontent.com/assets/18207232/21602049/0de38cf2-d1cb-11e6-9789-3a04284cf7c4.png)

期望的结果:
----

**Comment by Judystudy** [comment]
我来做
