### ISSUE TITLE
移库单对应的move_line行类型应该是internal

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1015]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----
此字段有default值out，因此view上对字段设置的context被此默认值覆盖，导致internal类型的move_line也被保存成了out类型

截图:
![image](https://cloud.githubusercontent.com/assets/1857069/21628960/d6df4c98-d25e-11e6-9da5-a3b478721e6f.png)

期望的结果:
----
去掉default，并检查所有view上的context，确保行取得正确的type值
另外，移库单的编号前缀改为 TRANSFER(注意检查test case)

**Comment by floraXiao** [comment]
已修改
