### ISSUE TITLE
收款单生成会计凭证未考虑外币

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1021]
操作系统及版本:
----
重现问题的步骤:
----
1.  http://best.gooderp.org/d/46

...

当前结果:
----
收款单生成的凭证，外币币种、外币金额、汇率都没有填充，借贷方金额应该是外币转换为人民币的金额

截图:
见帖子

期望的结果:
----

借：外币币种USD，外币金额120，汇率0.5，借方60 

贷：外币币种USD，外币金额120，汇率0.5，贷方60

**Comment by lilnn** [comment]
已测试
