### ISSUE TITLE
组装单上选择物料清单能正确带出明细行，但是保存后明细行会额外多一行

### ISSUE THREAD

**Issue by floraXiao** [osbzr/gooderp_addons#1025]
操作系统及版本:
----
重现问题的步骤:
----
1.
新建组装单，选择一个物料清单
2.
查看明细行，然后保存，会发现明细行自动增加组合件产品，导致审核时借贷方不平
3.

...

当前结果:
----

截图:
保存前：
![image](https://cloud.githubusercontent.com/assets/13793204/21635751/5b00fe00-d29a-11e6-8d73-4e2f1a55b31b.png)
保存后：
![image](https://cloud.githubusercontent.com/assets/13793204/21635772/69ea8fee-d29a-11e6-90e9-2978133384cf.png)

期望的结果:
----

**Comment by floraXiao** [comment]
已修改

**Comment by GoodERPJeff** [comment]
自己改出来的bug，呵呵
