### ISSUE TITLE
组装单、拆卸单、委外加工单审批两步，第一步投料，第二步产出成品

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1029]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----
投料和产出在一次审批时完成，对于投料来说是时间滞后了

截图:

期望的结果:
----
在产出成品之前投料，可以追加材料

**Comment by Judystudy** [comment]
我来做。
