### ISSUE TITLE
收付款单增加 核销行清零 按钮

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1036]
操作系统及版本:
----
重现问题的步骤:
----
1. 假设客户一个月有上百比欠款

2. 支付一次，支付其中的一笔

3.系统自动带出来的大部分核销记录都要清零

...

当前结果:
----

截图:

期望的结果:
----
使用这个按钮把之前带出来的核销行 【本次核销金额】 都改为0

**Comment by lilnn** [comment]
已测试
