### ISSUE TITLE
其他收支明细表 增加【账户】列，和【往来单位】一起放在类别前面。收支项目 改为 收支项

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1039]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by gilbert-yuan** [comment]
马上修复

**Comment by GoodERPJeff** [comment]
https://github.com/osbzr/gooderp_addons/commit/73260fee4a13a6bcdb0ad3908570f69d283b9a6a
