### ISSUE TITLE
盘点单行的修改

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1048]
操作系统及版本:
----
重现问题的步骤:
----
1. 按示例数据操作其他出入库和移库后新建盘点单

2.输入实际盘点库存

3.

...

当前结果:
----

已经查询过账面数量了，但是仓库、产品和日期还可以改

行上这么多字段实际上要求用户输入的只有两项  盘点库存 和 盘点辅助单位库存，非常不直观

截图:

期望的结果:
----

点击查询后，仓库、产品和日期不可修改

查询到的结果按 goods_id 和 lot_id 做一下排序再插入行，以免相同的产品不在一起

盘点库存 和 盘点辅助单位库存 两个字段设置为必输

字段的名称改一下：
 
账面数量
账面辅助数量

实际数量
实际辅助数量

差异数量
差异辅助数量

所有数字列都要有 sum

查询后每行的批号已经确定，为什么还需要 盘盈批号、盘亏批号两个字段？

**Comment by floraXiao** [comment]
已修改
