### ISSUE TITLE
批号状态表 应该叫 批次余额表，分组顺序改一下，先按 产品 分组再按 批次 分组

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1052]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----
http://best.gooderp.org/d/51/19

截图:

期望的结果:
----

**Comment by floraXiao** [comment]
已修改

**Comment by lilnn** [comment]
已测试
