### ISSUE TITLE
任务模块：主数据-项目里，未选择客户，在发票行点击生成发票需要报错

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1061]
操作系统及版本:
----
重现问题的步骤:
----
1.任务

2.主数据

3.项目

...

当前结果:
----

截图:

![image](https://cloud.githubusercontent.com/assets/18207232/21756103/a22f183c-d657-11e6-89ea-5de557c8f60a.png)

期望的结果:
----

**Comment by floraXiao** [comment]
已修改

**Comment by lilnn** [comment]
已测试
