### ISSUE TITLE
使用其他入库单导入期初数据时，如果成本为零，审核时报错

### ISSUE THREAD

**Issue by fanliugen** [osbzr/gooderp_addons#1067]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

![image](https://cloud.githubusercontent.com/assets/761509/21769617/8a88ec0e-d6ba-11e6-82de-96a7740073f8.png)

期望的结果:
----
别报错！

**Comment by lilnn** [comment]
已测试
