### ISSUE TITLE
组装单添加子件时无法添加系统中已加入的商品，只能显示前面160个

### ISSUE THREAD

**Issue by fanliugen** [osbzr/gooderp_addons#1078]
操作系统及版本:
----
重现问题的步骤:
----
1.组装单添加子件时无法添加系统中已加入的商品，只能显示前面160个

2.

3.

...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/761509/21879905/b5df3142-d8d6-11e6-90a4-7d5043298aec.png)

期望的结果:
----
在输入时可以自动补全，并在查看更多中看到所有商品

**Comment by GoodERPJeff** [comment]
https://github.com/osbzr/gooderp_addons/pull/1083

160是框架在many2one搜索更多时给的limit限制，为性能考虑。进一步输入搜索条件可以找出所有产品
