### ISSUE TITLE
仓储人员取消勾选查看产品成本的权限，在采购入库单中还是可以查看价格

### ISSUE THREAD

**Issue by fanliugen** [osbzr/gooderp_addons#1079]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/761509/21882365/1a96fc42-d8e5-11e6-903f-24be532cb822.png)

期望的结果:
----
仓储人员只能看到相应的货的数量，不能看到商品的采购价

**Comment by floraXiao** [comment]
这是因为采购入库单上的单价、含税单价以及产品成本没有加这个组的限制，实际这里的产品成本应该加上这个组的，但是单价和含税单价不应该在产品成本组中

**Comment by floraXiao** [comment]
已修改

**Comment by floraXiao** [comment]
https://github.com/osbzr/gooderp_addons/pull/1095/commits/c7298dc3c8bb6367010512df7290ac95ef29c221

**Comment by GoodERPJeff** [comment]
测试通过
