### ISSUE TITLE
标准安装应该初始化一些最常用的基本单位，辅助单位

### ISSUE THREAD

**Issue by szufisher** [osbzr/gooderp_addons#1086]
操作系统及版本:
----
重现问题的步骤:
----
1.标准安装，不加载演示数据

2.

3.

...

当前结果:
在新建商品时，基本单位及辅助单位下拉清单为空，需要手工创建

截图:

期望的结果:
像科目一样，在安装时，初始化一些最常用的基本单位，如个，支，片，件，套，包，捆，瓶，打，箱，米，公斤，克等

**Comment by GoodERPJeff** [comment]
科目是每个公司都用的，但是每个单位都不可能保证在每家公司都可用，中文的单位比较具体，不像英文有个PC具备多层含义。考虑到实施过程中导入产品之前要导入计量单位，二者可能用id关联，所以系统完全不自带才最有自由度。
