### ISSUE TITLE
购货订单表单界面增加关联到入库单和结算单(发票)的链接

### ISSUE THREAD

**Issue by szufisher** [osbzr/gooderp_addons#1087]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
打开购货单表单界面，没有跳转到入库单和结算单的按钮或action

截图:

期望的结果:
在购货单界面增加跳转到入库单和发票的按钮

**Comment by GoodERPJeff** [comment]
同样适用于销货订单
