### ISSUE TITLE
在出错对话框增加按钮直接跳转到导致出错的主数据页面

### ISSUE THREAD

**Issue by szufisher** [osbzr/gooderp_addons#1088]
操作系统及版本:
----
重现问题的步骤:
----
1.新增供应商，在供应商类型栏位通过下拉菜单一个国内类别，填写其他必填栏位，保存该供应商

2.为上述新建的供应商新增一个购货订单，并审核

3.审核入库单

...

当前结果:
出错对话框，提示信息:请配置国内的科目

截图:

期望的结果:
在上述出错对话框上增加一个按钮，直接跳转到供应商类型维护界面，这样就可以更容易定位及解决问题了。

这里只是一个典型案例，可以考虑对出错对话框做类似统一处理，这样整个系统出错处理方面的易用性会有很大的提升。

**Comment by GoodERPJeff** [comment]
考虑到权限问题，拆分系统配置数据、主数据和业务数据的维护权限，使得大多数初级用户只关注日常业务数据，配置交给内部管理员或外部顾问。

技术上这样的修改需要把raise error改成 wizard + return action，代码量和复杂度大幅提升了。
