### ISSUE TITLE
默认只显示草稿状态的采购入库单

### ISSUE THREAD

**Issue by szufisher** [osbzr/gooderp_addons#1089]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
进去采购入库单界面，默认会显示所有的入库单

截图:

期望的结果:
将草稿状态设为默认的过滤条件，进入入库单界面，默认只看到草稿状态的单子

**Comment by gilbert-yuan** [comment]
这应该属于个性化的需求吧？ 不同状态的单子是加过滤区分还是设置不同的菜单，这个也是要看最终用户的喜好。

**Comment by GoodERPJeff** [comment]
系统上线后单据量较大，确实大多数情况下只需关注订单生成的待处理出入库单。这个需要实现一下，顺便也改一下销售发货单的搜索视图。
