### ISSUE TITLE
新建数据库，勾选演示数据，会计凭证示例和配置类别有错误

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1094]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----
![image](https://cloud.githubusercontent.com/assets/18207232/23004900/36cc8836-f434-11e6-827a-e378614a229a.png)
![image](https://cloud.githubusercontent.com/assets/18207232/23004982/8e22b146-f434-11e6-8252-aa5808bd6ca1.png)

截图:

期望的结果:
----

**Comment by GoodERPJeff** [comment]
已测试通过
