### ISSUE TITLE
money模块完善

### ISSUE THREAD

**Issue by yxs1205** [osbzr/gooderp_addons#1112]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:1.partner.py所有方法加功能注释
2money_order.py所有方法加功能注释
3..money_order.py 55行注释应改为修改时......
4.153行不知道有什么用
5.121行 help的写法改一下
6.131行结算单行改为核销行
7.164.报错信息中的逗号可以去掉，以及感叹号。
8.231行报错信息改为付款金额
9.273行报错信息改为收款金额
10.300行的代码or后面重复了，可以去掉
11.379,行help只是发票号。

----

**Comment by floraXiao** [comment]
已修改
