### ISSUE TITLE
money.order.py需要修改的地方

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1120]
操作系统及版本:
----
重现问题的步骤:
----
1.481行，描述：结算单明细改为待核销行

2.462行报错，去掉感叹号

3.485行help 原始单据行对应的收付款单改为待核销行对应的收付款单

4.495行Help 原始单据行对应的结算单编号改为待核销行对应的结算单编号

5.492行 string=u'结算单编号中的编号俩字去掉

6.498行，503行，506行，509行，514行的help 原始单据改为待核销行

7.529行creat方法可以去掉

8.538行，unlink的方法可以做统一的处理，只能删除草稿状态的单据

9.562行，string=u'预收单行改成string=u'预收/付款单行

10.564行，help 业务伙伴有预付款单，自动带出，用来与应收/应付款单核销改为业务伙伴有预收/付款单，自动带出，用来与应收/应付款单核销

11. 638行和639行可以删除掉

12.701行，报错'转出客户和转入客户不能相同!\n转出客户:%s 转入客户:%s'改为业务伙伴和转入往来单位不能相同!\n转出客户:%s 转入客户:%s'

13.748行，去掉编号俩字，750行的help核销单预收付款行对应的预付款单编号改为 核销单预收/付款行对应的预收/付款单

14.755行 help 预收付款单的预收金额改为 预收/付款单的预收金额

...

当前结果:
----

截图:

期望的结果:
----

**Comment by floraXiao** [comment]
已修改
