### ISSUE TITLE
money模块的一些小问题

### ISSUE THREAD

**Issue by yxs1205** [osbzr/gooderp_addons#1121]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
core.groups.xml 71行 模块中的管理服务改为管理收支项
74行改为 用于显示收支项类

money_order_view.xml tree string 和form string 后面改为汉字。
48行 核销金额清零manager组去掉。 高亮去掉。
49行的只读可以去掉，多余。
99行 nolabel 不需要写。
174-190核销明细的tree视图删掉
193行 TOP改为小写
198行 state 去掉
228行 search视图的 state去掉
229行 expand去掉

other_money_order.py
39行or后面的不需要
63行 help其他收支单状态标识
111行 用float_compare比较
140行 服务改成收支项
156行 服务改成收支项

other_money_order_view.xml
10行 string去掉

report_date.xml 20 41行的高亮去掉。
----

**Comment by floraXiao** [comment]
已修改
