### ISSUE TITLE
money transfer order.py 以及view文件中的一些问题

### ISSUE THREAD

**Issue by yxs1205** [osbzr/gooderp_addons#1124]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:money_transfer_order.py
31-34行不需要
51行help 改成资金转账单
58~59readonly 和 states 不需要
69行 加一个ondelete
92行 本次转出余额改为金额
102行本次转出余额改为外币金额
110行  self 向前缩进
119行多两个空格
122行转出改为外币金额
120-140行 每一个else后面加一个注释
129,136行 转出余额改为金额
160行 help 转出或转入的外币金额
163行 help 转出或转入的金额

审核方法的else加注释
系统中所有和零进行比较的改为 floot is zero
两个浮点数比较的改为compare

money_transfer_order_view.xml
27行statusbar visible 删掉
55-60行 group组删掉
63行 nolabel去掉
70行上面加一个最后修改人字段
89.91行 删掉
别的分组 group 也可以去掉

partner.py
9行去掉
75-78行 去掉
95行 去掉
109行 去掉

generate_accounting.py
所有的方法加注释
50,71行的Line 没用用到，写到注释中
77,120行的source ids 没用
105行上面 加一个如果客户类别不填就报错
138行 上面加一个供应商的报错
  103行写成false
----

**Comment by floraXiao** [comment]
partner.py 75-78行 不能去掉，其他地方用到了

**Comment by floraXiao** [comment]
已修改

**Comment by floraXiao** [comment]
已修改
