### ISSUE TITLE
Money models generate_accounting.py文件里需要修改的地方

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1126]
操作系统及版本:
----
重现问题的步骤:
----
1.227行加注释：“生成初始化凭证时，不生成往来单位对方的科目”

2.243行，479行，495行，511行冒号前的空格去掉

3.247行和249行加注释

4.263行去掉 or debit / vals.get('amount')，295行去掉or credit / vals.get('amount')

5.311行的报错，去掉感叹号，系统参数改为公司，392行，433行，279行系统参数改为公司

6.322行ondelete="set null"改为ondelete="restrict“

7.371行，借方的和直接取单据的金额，total_amount,412行修改同371行

8.478行，报错：正确结汇改为请输入外币金额

9.477行，self.line_ids改为line

10.486行不需要写外币金额和汇率，509的修改同486行

当前结果:
----

截图:

期望的结果:
----

**Comment by floraXiao** [comment]
已修改
