### ISSUE TITLE
money.view generate_accounting.xml/money reort bank_statements.py需要修改的地方

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1134]
操作系统及版本:
----
重现问题的步骤:
----
1.27-40行不用写继承，移动到基础视图中

2.55-64行 money_order_form同上

3.66-86行，同上

4.38行加注释“this balance 增加这个字段为性能考虑”

5.去掉19行，21行，22行，保留20行，25行加号去掉

6.bank_statement.view.xml 12行attrs去掉，balancen改成this balance

7.113行查找原始单据的方法可优化

8.141行去掉

...

当前结果:
----

截图:

期望的结果:
----

**Comment by floraXiao** [comment]
已修改
