### ISSUE TITLE
质检模块

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1148]
当前结果:
----

出入库无质检环节

期望的结果:
----
在 wh.move 上增加 qc_result 字段，“”质检报告“”，二进制类型，允许用户上传文档，审核后不可编辑。使用 widget="pdf_viewer"  显示在“备注”字段下方

审核时读取质检规则表，根据 单据类型、出库库位、入库库位 三个条件取是否需要质检，如需要且 qc_result 字段为空，报错：“”请先上传质检报告“”

**Comment by lilnn** [comment]
组装单、拆卸单和委外加工单没有提示‘上传质检报告’

**Comment by lilnn** [comment]
已测试
