### ISSUE TITLE
商品保质期管理

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1149]
当前结果:
----
采购入库 生产入库 其它入库 都无法输入 保质期截止日期

期望的结果:
----
在wh.move上增加字段，对 move_line 类型为in或internal的时候由用户输入，并显示在库存调拨的列表上

增加用户组 “”管理保质期“”

其他功能慢慢增加

**Comment by lilnn** [comment]
已测试
