### ISSUE TITLE
warehouse goods.py里需要修改的地方

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1150]
操作系统及版本:
----
重现问题的步骤:
----
1.第10行默认值不需要加

2.商品界面上“每批号数量为1”改为“序列号管理为1”

3.其他出库单应产生负库存

4.加注释（75行、80行、84行方法加注释，122行变量加注释）

...

当前结果:
----

截图:

期望的结果:
----

**Comment by floraXiao** [comment]
已修改
