### ISSUE TITLE
warehouse move.py里需要修改的地方

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1151]
操作系统及版本:
----
重现问题的步骤:
----
1.261行报错，ean改为条码

2.111和114行不要为Id来比较

3.105和118两个方法放在一起

4.196、200、212、216行应分采购和销售两种情况

5.187-203行属性上条码和商品上条码这两种情况可优化

6.342行和349行else去掉，343行、344行、350行可以往前提

7.343行不需要取wh.move，直接用self调用函数

8.339行删掉，369行改为vals=

9.361行cost_unit的值为0

...

当前结果:
----

截图:

期望的结果:
----

**Comment by floraXiao** [comment]
已修改
