### ISSUE TITLE
资金-其他收支明细表，类别和收支项显示的内容不正确

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1160]
操作系统及版本:
----
重现问题的步骤:
----
1.资金

2.报表

3.其他收支明细表

...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/18207232/23930060/ef80677c-0964-11e7-8939-c099e4dd6f77.png)

期望的结果:
----

**Comment by floraXiao** [comment]
已修改

**Comment by lilnn** [comment]
已测试
