### ISSUE TITLE
账户输入期初余额生成的其他收入单取的是其他支出单的编号

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1166]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by GoodERPJeff** [comment]
https://github.com/osbzr/gooderp_addons/commit/c3acf676c401f5874519fe09469ad3b5aa9ccf96

**Comment by lilnn** [comment]
已测
