### ISSUE TITLE
任务模块两处修改

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1179]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----
看不到上次记录日志的时间

截图:

期望的结果:
----

工作日志列表增加筛选 “今日”

今日-工作日志行最后增加创建日期只读字段

**Comment by GoodERPJeff** [comment]
测试失败

今日 应该是当前日期，你写的是小于当前系统时间，总是筛出所有记录。

分组应该要基于created by用户分组，而不是assign_to分组

**Comment by lilnn** [comment]
已测试
