### ISSUE TITLE
人力资源-工资-员工工资，存在修正凭证，报错不太明确

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1186]
操作系统及版本:
----
重现问题的步骤:
----
1.人力资源

2.工资

3.员工工资

...

当前结果:
----
![image](https://cloud.githubusercontent.com/assets/18207232/24286929/50859a5c-10b2-11e7-9aad-69a5f98bd886.png)

![image](https://cloud.githubusercontent.com/assets/18207232/24287137/4fe3da72-10b3-11e7-9cfb-2461475a4af6.png)

截图:
审核后修正凭证变为00083，原为00082，

期望的结果:
----
报错"存在修正计提凭证，请使用计提来补充原计提凭证“

**Comment by GoodERPJeff** [comment]
还是看不懂啥意思。。。

**Comment by GoodERPJeff** [comment]
@lilnn 你这里提的是两个问题，标题也没写清楚

问题1、当点击【反计提】按钮时，如果该工资单有调整凭证（也就是说不止计提过一次），是不允许做【反计提】操作的，而是推荐用户修改数据后再点【计提】按钮来重新生成调整凭证。也就是反计提这个按钮是只为第一次计提生成的会计凭证服务的（为什么这样设计，跟跨期有关系？）。所以从源码看报错应该是“存在修正计提凭证，请点击计提按钮来更新修正计提凭证”

问题2、当点击【审核】按钮时，会再调用一次计提（是因为担心“未审核”状态有人改了工资数据但没点计提按钮）。如果该工资单有调整凭证，则会删除之前的调整凭证，创建新的调整凭证（无论上次计提后数据是否有变化）。所以你看到调整凭证编号变了。这除了引起凭证断号也没有其他坏处，建议不做修改。

@xuanyimin 能否讲一下第一次计提后，如果数据有修改，用户如何决定是点【反计提】按钮（删除计提工资凭证）还是直接点【计提】按钮（生成修正计提凭证）？

**Comment by xuanyimin** [comment]
上个星期天改过了，不出那个警告了，同月就重新生成，跨月就生出修正！




发自网易邮箱大师
在2017年03月24日 23:10，开阖软件 Jeff Wang 写道：

@lilnn 你这里提的是两个问题，标题也没写清楚

问题1、当点击【反计提】按钮时，如果该工资单有调整凭证（也就是说不止计提过一次），是不允许做【反计提】操作的，而是推荐用户修改数据后再点【计提】按钮来重新生成调整凭证。也就是反计提这个按钮是只为第一次计提生成的会计凭证服务的（为什么这样设计，跟跨期有关系？）。所以从源码看报错应该是“存在修正计提凭证，请点击计提按钮来更新修正计提凭证”

问题2、当点击【审核】按钮时，会再调用一次计提（是因为担心“未审核”状态有人改了工资数据但没点计提按钮）。如果该工资单有调整凭证，则会删除之前的调整凭证，创建新的调整凭证（无论上次计提后数据是否有变化）。所以你看到调整凭证编号变了。这除了引起凭证断号也没有其他坏处，建议不做修改。

@xuanyimin 能否讲一下第一次计提后，如果数据有修改，用户如何决定是点【反计提】按钮（删除计提工资凭证）还是直接点【计提】按钮（生成修正计提凭证）？

**Comment by GoodERPJeff** [comment]
经过昨天的讨论，有以下几点设计需要修改：

1、去掉【反计提】按钮，在用户点击【计提】按钮时，如计提凭证已存在，判断当前期间是否与工资期间相同，如相同，反审核计提凭证并重新生成计提凭证；如不同，生成并审核修正凭证。

2、【计提】按钮生成（计提或修正）会计凭证后直接审核此会计凭证

3、删除工资单同时（反审核并）删除对应的会计凭证

**Comment by xuanyimin** [comment]
要先作废吧 不能直接删除




发自网易邮箱大师
在2017年03月28日 10:14，开阖软件 Jeff Wang 写道：

经过昨天的讨论，有以下几点设计需要修改：

1、去掉【反计提】按钮，在用户点击【计提】按钮时，如计提凭证已存在，判断当前期间是否与工资期间相同，如相同，反审核计提凭证并重新生成计提凭证；如不同，生成并审核修正凭证。

2、【计提】按钮生成（计提或修正）会计凭证后直接审核此会计凭证

3、删除工资单同时（反审核并）删除对应的会计凭证

**Comment by lilnn** [comment]
生成的修正凭证，列表视图显示的总计和借贷方金额不一致

**Comment by lilnn** [comment]
已测试
