### ISSUE TITLE
商机界面增加字段

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1197]
客户 many2one partner

预计采购时间 date

标签 这个也加在任务上 many2many 可选值

产品 many2many  名称|数量|单价|描述

报价总额 compute 然后 track_visibility

成功原因分析 many2one selection 可选值，预先data导入以下数据：

* 产品报价准确
* 客户需求分析到位
* 方案专业
* 有发展内线
* 在沟通期间响应及时
* 产品的表现力优于竞争对手
* 客户预算充足
* 公司品牌影响力较大
* 有关键口碑介绍

**Comment by lilnn** [comment]
已测试
