### ISSUE TITLE
所有单据的经办人字段应指向user

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1200]
不应该是 staff_id 而应该是 user_id 指向 user对象，这样后续过滤和写规则权限还有统计分析都会比较一致。

销售订单

销售调整单

采购订单

采购调整单

。。。

其他模块的逐个看一下吧，单据都要

**Comment by lilnn** [comment]
采购订单/入库单/退货单/变更单，销售变更单，其他入库单/出库单，组装单/拆卸单/委外加工单没有经办人字段

**Comment by lilnn** [comment]
已测试
