### ISSUE TITLE
成本核算逻辑修改

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1207]
* 科目的成本类型增加一个可选值（成本类），4开头的科目改成成本类
* 销售发货单、退货单审核时生成会计凭证 借：主营业务成本（核算分类上） 贷：库存商品（商品上）
* 其他出库单生成会计凭证 借：类别对应的客户 贷：库存商品（商品上）
* 组装单、拆卸单、委外加工单材料出库生成会计凭证，借：生产成本-基本生产成本（核算分类上） 贷：库存商品（商品上）
* 月底成本结转生成的凭证，算出借贷方金额后，借贷方金额全部减去本期间库存商品科目（所有商品类别涉及的科目）贷方金额合计。

**Comment by GoodERPJeff** [comment]
还差 委外和拆卸单没有实现，加油

**Comment by lilnn** [comment]
已测试
