### ISSUE TITLE
会计凭证筛选【本期报错】

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1211]
操作系统及版本:
----
重现问题的步骤:
----
1. 会计-凭证-会计凭证

2. 高级筛选-筛选-本期

3.

...

当前结果:
----
ValueError: Invalid field u'vdate' in leaf "<osv.ExtendedLeaf: (u'vdate', u'>=', u'2017-03-01') on voucher (ctx: )>"

截图:

期望的结果:
----
不报错且返回正确结果

**Comment by lilnn** [comment]
已测试通过
