### ISSUE TITLE
凭证无备注会计很迷茫

### ISSUE THREAD

**Issue by xiaogutou17** [osbzr/gooderp_addons#1246]
操作系统及版本:
----
重现问题的步骤:
----
1..从每一个模块做单子，在明细行和单子上都写上备注，到会计模块生成会计凭证

2.查询明细账

3.

...

当前结果:
----
1.做完单子点击保存以后在单据列表上看不到备注内容2.生成的会计凭证也看不到备注内容3.查询明细账也没有备注内容

截图:截图:
![Uploading image.png…]()1.做完单子以后单据列表看不到备注内容，查询单据的时候很难找到

![Uploading image.png…]()2.生成的会计凭证没有备注内容，看到凭证不知道具体是什么业务

![Uploading image.png…]()3.查询明细账没有备注内容，导出数据提供给别人看不明白

期望的结果:
----
![Uploading image.png…]()希望在明细账、会计凭证、及每一个模块的生成的单据列表上都增加一项备注，方便查询凭证

**Comment by floraXiao** [comment]
https://github.com/osbzr/gooderp_addons/pull/1245/commits/5e2c92b0ac165f330c7349695bbde33092fb424c

**Comment by floraXiao** [comment]
https://github.com/osbzr/gooderp_addons/pull/1245/commits/ac1ea8af31001f19f5f87f8db7f5f4e557bd930f

**Comment by lilnn** [comment]
其他收支单和其他出入库单列表上显示备注信息；
生成会计凭证后，单子上的备注自动添加到摘要上面；
明细账上也显示在摘要上面。
