### ISSUE TITLE
库存商品按类别排序问题

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1296]
操作系统及版本:
----
window7

重现问题的步骤:
----

1.依次点击 仓库——商品  进入产品页面
2.点击产品类别  按产品类别排序
3.

...

当前结果:
----

未按照产品分类的名称排序
好像是按照类别ID排序

截图:

![qq 20170510150723](https://cloud.githubusercontent.com/assets/10705547/25887001/ccccf326-3592-11e7-9a2e-e2315605506a.png)

期望的结果:

希望安装产品类别的名称排序

----

**Comment by zhhangtaao** [comment]
非常感谢您如此快速的回复。

但是我将程序升级到最新版本之后问题没有解决，和之前的状况一致。

可能之前的截图描述的不清晰，重新截了一个图 麻烦看一下。谢谢

![20170512212610](https://cloud.githubusercontent.com/assets/10705547/26000016/d7edb8ee-3759-11e7-9670-dc3e341127b1.png)

**Comment by GoodERPJeff** [comment]
刚刚合并，您再拉代码重启测试一下。

**Comment by zhhangtaao** [comment]
回复太神速了   我马上测试一下  非常感谢

**Comment by zhhangtaao** [comment]
完美解决，非常感谢。
