### ISSUE TITLE
warehouse_wave模块

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1312]
实现立体仓库捡配打包功能

核心对象：
----

wh_wave { 拣货单号(char)、订单类型(char)、承运商(char)，状态(未打印、已打印、已完成) }

wh_wave_line { 商品(many2one)、捡货数量(float)、移库单行(many2many) }

拣货单行需要根据货物的位置排序

location { 货位号(char)， 仓库（many2one）,商品(many2one) }

修改现有对象
----

sell.delivery增加 wave_id(many2one) pack_no(int)
goods增加 loc_ids

流程：
====

分配
----

在delivery列表上勾选，更多-创建拣货单，填充delivery的相关字段，创建wave，wave行关联对应产品的move_line

打印
----

图片稍后上传 行上的其他字段从商品取关联值

打包
----
* 扫描面单，下方显示此发货单对应的行作为待打包信息
* 扫描商品条码，更新对应行已打包数量
* 点击 【完成】按钮，如全部行已打包数量 = 待打包数量，自动审核对应delivery

删除拣货单
----
拣货前，拣货单可删除，相关delivery被释放以重新分配
如果任一相关delivery已打包（已审核），报错，不允许删除此拣货单。

**Comment by gilbert-yuan** [comment]
打包功能描述不清楚..

**Comment by leangjia** [comment]
前排支持。
