### ISSUE TITLE
GoodERP几个小问题

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#1318]
操作系统及版本:
----
重现问题的步骤:
----
1.应用-进入模块，动作下拉‘设置默认值’无效（具体不知道什么作用）
模块都是只读的，默认值无意义

2.资金-其他出库单/其他入库单/付款单/收款单/资金转账单的结算账户下拉可新建帐户，是不是不应创建？   
只有出纳可以新建账户，其他人只能读和改

3.资金-设置-创建新客户和采购模块新建供应商上面有名称，而销售模块和资金模块新建供应商无
供应商的form加上名称字段的label

4.采购和仓库模块主数据的子菜单商品，点击进去上面是产品，应统一改成商品
全局搜索一下，凡是出现产品字样的地方统一改成商品

5.人力资源-员工-合同里的选项卡岗位就改成职位，与设置里的职位一致
合同标签页表格的最后一列label改一下

6.仓库-质检规则无效
质检规则三个字段应该都必输

7.会计-设置-默认设置下的选项：自动重置凭证号    凭证号重置间隔	重置后起始数字三项无效，点击应用，在结账会生效，但下个月重置凭证号还不是从1开始。

似乎默认配置里带过来的“自动重置凭证号”的值代码里取不到

8.资金转账单列表视图看不到金额
已修改
...

当前结果:
----

截图:

期望的结果:
----

**Comment by gilbert-yuan** [comment]
1. 设置默认值, 当前页面的值作为默认值,(不支持one2many many2many等字段的值的设置).可以简化操作,比如 会计凭证页面,凭证日期默认是当前日期,如果有一批凭证是以前的某个日期,就可以手动选择那一日期,完成凭证保存,然后设置默认值.以后新建的会计凭证就是 你选择的那个日期
