### ISSUE TITLE
您好，请问这个链接是否是未经许可搜集客户资料？

### ISSUE THREAD

**Issue by neroxps** [osbzr/gooderp_addons#1337]
我部署了 SSL，发现有两个链接失败，都是联通 gooderp.org 的，我觉得你们将 odoo 本地化这个十分好。
但是我又有顾虑，虽然代码是公开的，你们在官网上说免费提供给客户使用，但至少在使用之前得有个隐私协议吧，搜集使用者的公司信息方便以后针对销售作为一个免费软件我可以理解，但是至少得通知一下。

只要登录首页都会返回一个客户信息的 URL 到贵公司的网站，里面明文写上了公司地址，电话号码。

这样对一个 ERP 软件是否真的合适？

# 希望能谨慎对待此事，ERP 数据对一家公司来说尤为重要，我相信贵项目对其他的财务数据之类不会做这样的搜集行为，但在未通知客户的情况下搜集客户录入的信息（不管是什么信息），都会对潜在客户带来很坏的影响。

**Comment by GoodERPJeff** [comment]
这个是针对action执行次数的统计，为了形成我们网站首页那个计数，以及测算哪些功能使用率最低我们会降低开发权重。

对于付费用户，我们已明确告知并有技术手段可以去掉这个统计功能。对于试用客户或者未付费客户，我们没有途径也没有精力一一通知，希望理解。

如果你有更好的通知方式建议，请告诉我们。保密协议就免了，我不会和一个陌生人签什么协议的。

**Comment by neroxps** [comment]
根本不需要签协议。

其实我理解你们的做法，但是至少弹出一个对话框告诉用户，你们搜集的仅仅是为了检测模块使用率。因为作为一般用户并不懂这个是什么，至少一个隐私说明不是很难吧？如果用户同意，那么可以继续使用，不同意，那么就没法使用。仅此而已~

我相信只要说明了，都是可以理解的。主要是没说明。

**Comment by GoodERPJeff** [comment]
在哪个时点哪个位置弹对话框？

最初的设想是在新建数据库的界面上加上一大段文字说明，但是因为那一块是框架的源码，改动会造成同步困难。不过这个貌似是第一入口，加在这里最合适。

**Comment by neroxps** [comment]
嗯就是这第一步。
或者其他醒目的位置来个隐私声明也可以。

主要是今天刚推荐给领导，发现这个东西领导要是发现了不好交代。

**Comment by GoodERPJeff** [comment]
仅针对未付费客户，购买标准服务后可去除。
https://item.taobao.com/item.htm?id=550421434967
