### ISSUE TITLE
月末结帐没将生成的主营业务成本结转利润！

### ISSUE THREAD

**Issue by xuanyimin** [osbzr/gooderp_addons#1372]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:
![354b34be-cb62-47f6-ad23-f073fa181dd2](https://user-images.githubusercontent.com/19392611/28348759-40bb0bd2-6c71-11e7-933f-28993c2c8a53.png)

期望的结果:
----

**Comment by GoodERPJeff** [comment]
发出成本怎么是贷 -25641.03  产品发出了，库存账面金额反而增加了？

**Comment by GoodERPJeff** [comment]
无法重现，暂时关闭
