### ISSUE TITLE
good_shop

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1395]
参照 https://github.com/odoo/odoo/tree/10.0/addons/website_sale

客户可自行下单

**Comment by yangxunbo** [comment]
后台无法做电商前端的分类，需要在商品档案中增设商品电商前端的分类字段。

**Comment by GoodERPJeff** [comment]
这个分类应该可以直接用商品分类吧，另搞一套不太合适

**Comment by yangxunbo** [comment]
这样也是可以的，我是按照原来odoo的做法是单独有个公开分类这个东西来说明的，如果你把他与产品分类融合一起也是不错的方案！～
