### ISSUE TITLE
关于退货逻辑异常的bug

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1414]
操作系统及版本:ubuntu14.04
----
重现问题的步骤:
----
1.采购开单入库，一共采购2个产品，其中一个产品是勾选了批次，数量大于1即可

2.退货，默认是退2个产品，然后删除一个明细，只退一个，然后审核

3.再回到原单，退另外一个产品，提示已经全部退货，实际该单据还有一个商品未退货

...

当前结果:
----
退货的逻辑有问题，还有一个没有办法追溯，改单据的出入库情况，默认采购单只能看到采购入库，没有办法看到采购退货

截图:

期望的结果:
----
1、解决退货的逻辑问题
2、添加单据关联，可以在原始单据上查看单据的全部记录，包括入库和出库的

**Comment by GoodERPJeff** [comment]
原来的程序逻辑有很大的问题。因为按钮功能是从一个项目上复制过来的，那个项目客户的产品全部启用属性，所以功能移植到gooderp核心模块没有考虑无属性的产品和批次。现已修复。

另外，根据入库单生成退货单时，没有复制订单id，所以订单上点击按钮不会显示退货单。也已修复。美中不足这里列表上退货单和入库单都是正数，不太直观。

另外，退货时能直接从订单原始的单据复制批号，这是新增的特性，比较好用。

**Comment by GoodERPJeff** [comment]
已修复，请测试

**Comment by lonelyleaves** [comment]
有新的问题，采购21个产品，入库，然后生成退单，修改退货数量为11，审核，重新回到采购单，查看关联的单据，发现又生成了一张数量为11的入库单，单据为草稿状态
