### ISSUE TITLE
参照Max项目实现一个报价单对象

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1434]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by GoodERPJeff** [comment]
![image](https://user-images.githubusercontent.com/1857069/33533698-cefc1192-d8dd-11e7-882a-c36410908a16.png)

**Comment by jkhu99** [comment]
销货订单里，选中客户，填入型号后，能自动填写单价吗？有了报价单，销货订单是否不能随意修改单价了？
