### ISSUE TITLE
P1, 委外加工单里应有“组合件商品”的批号输入。

### ISSUE THREAD

**Issue by james-shang** [osbzr/gooderp_addons#1436]
justification: 有入库按钮也应该有批号输入. 就像采购入库单里的入库单行有批号输入一样。
user case: 用户的商品plc中选择了批号管理。 用户委外加工单 加工 plc产品。
![out](https://user-images.githubusercontent.com/13283733/30236809-33559a72-9555-11e7-96ee-323b1cdba571.png)

**Comment by lonelyleaves** [comment]
只要这个成品设置了批次，只要和这个产品有关联的stock_move都应该会有批次号，这个批次应该是在入库的时候才有 你看下是不是
