### ISSUE TITLE
主数据导出增加内置导入模板

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1450]
操作系统及版本:
----
重现问题的步骤:
----
1、商品列表
2、创建一个商品
3、导出
4、选择字段
5、导出为模板文件添加数据后导入
...

当前结果:
----
要取得一个模板必须要先输入至少一个商品然后选择字段再导出。

截图:

期望的结果:
----
每个主数据对象的导出界面内置一个标准字段列表

**Comment by GoodERPJeff** [comment]
![image](https://user-images.githubusercontent.com/1857069/30998271-d7c8c3ae-a4ff-11e7-82f8-7dca3376ef0c.png)

**Comment by leangjia** [comment]
一幅图胜过千句话

**Comment by GoodERPJeff** [comment]
ir.exports这个表
字段是 ir.exports.line
xml往里插数据就好了
记得要noupdate='1'

**Comment by lonelyleaves** [comment]
是否可以考虑直接增加表单编辑ir.exports,8有类似的模块
