### ISSUE TITLE
关于货品分类的显示问题

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1455]
----
问题:
----
产品分类这个太简单，建议参考odoo，有视图有，有常规，视图才可以建下级产品分类，常规是最底层分类，增加备注字段，可以方便查看分类的具体信息，比如这个分类的商品应该是哪些产品等！同时产品选择分类的时候只能选择最底层的产品分类
当前结果:
----

期望的结果:
----
完善货品分类信息

**Comment by GoodERPJeff** [comment]
这个很简单啊，你来改吧。这样改没问题，欢迎！

**Comment by lonelyleaves** [comment]
已提交
