### ISSUE TITLE
关于销售开单增加最近的销售价、平均价的问题

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1512]
销售开单时，可以显示该客户最近一次拿货的销售单价

**Comment by GoodERPJeff** [comment]
jeff wang(85822082) 11:38:30odoo框架不太好做这种
--
jeff wang(85822082) 11:39:14float上要悬浮显示两个可选值还要支持输入
jeff wang(85822082) 11:39:41很多时候单价是从其他条件带出来的单值，而不是直接输入
jeff wang(85822082) 11:39:57光标就不进这个格子
落叶随风(383082640) 11:40:38有个折中的办法 在末尾加个字段 可以展示
落叶随风(383082640) 11:40:45单价还是另外输
落叶随风(383082640) 11:40:49这样是不是就简单一些 /
jeff wang(85822082) 11:46:09备注字段
jeff wang(85822082) 11:46:25现在没什么人用，可以干这个
落叶随风(383082640) 11:46:46谢谢了
落叶随风(383082640) 11:46:52业务员在提这个要求
落叶随风(383082640) 11:47:03我觉得这个也是一个比较不错的功能
jeff wang(85822082) 11:47:14这个不会做在标准产品里的
