### ISSUE TITLE
关于检测库存为负不允许出库功能

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1537]
在一个公司内部会存在有些产品不允许出现负库存，有些可以出现，比如主要产品是肯定不能负库存，但是主要产品的配件是可以负库存，因为会存在一种情况就是从成品里面拿配件单独销售，但是拆解单回需要新建一个没有配件的成品的名称 也比较麻烦，如果把允许库存为负这个功能做到产品上会更加方便

**Comment by GoodERPJeff** [comment]
负库存会造成成本计算的遗漏，不推荐使用。
商品上字段太多了，这个就不加了吧。
