### ISSUE TITLE
关于单据作废添加字段追溯作废人

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1553]
现在单据的作废状态变更不会记录变更人，建议增加字段追溯，可以知道是谁作废的单据

**Comment by GoodERPJeff** [comment]
这个不需要加字段，应该是 state 被消息机制监控了，消息里就有了。 

我们仓库单据的消息机制好像不太完善。

**Comment by lonelyleaves** [comment]
建议状态字段加追溯
