### ISSUE TITLE
关于防止用户暴力穷列举破解用户的登陆账号密码

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1563]
gooderp为bs架构，本身odoo没有相应的防止用户暴力破解功能，建议增加限制用户暴力破解用户密码功能：同一个ip/账号连续输错几次错误的密码，增限制用户登陆，这个时间以几何倍数递增，第一次3min，第二次10分钟。。。。，8有相应的模块，已发官方群，期待更新

**Comment by GoodERPJeff** [comment]
这种模块应该不会放在 gooderp_addons 这个库里的

这个是better，不是good
