### ISSUE TITLE
关于打印模版尺寸问题

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1564]
我的打印机是1/3的打印纸，纸张尺寸为宽22*9.3，我设置好打印尺寸以后调好模版，生成的格式是对的，尺寸表头什么的都ok，但是打印的时候变成了竖向的，打印的内容在22的中间大概9.3的部分了，不知道是打印问题还是模版问题

**Comment by GoodERPJeff** [comment]
这个是word的打印设置问题吧，请检查一下或者翻阅word文档
