### ISSUE TITLE
Open Collective

### ISSUE THREAD

**Issue by asood123** [osbzr/gooderp_addons#1569]
Hi there - Thanks for applying to start an open collective. Would you please let us know what you would use the money for and whether you are fine in receiving and expensing funds in USD? We don't offer RMB yet.

Thanks
Aseem

**Comment by GoodERPJeff** [comment]
Thanks for your kindness reply. 

We use many python library in our project, I need feedback not only bugfix but also donation to them. We are depends on their work to migrate from python 2.7 to python 3.  

Yes, We will use the money to donate python projects we depends on. So USD is fine, thank you.

**Comment by asood123** [comment]
Ok, I have enabled your collective and submitted initial PR to show backers or sponsors on your README. Please let me know (on the PR) if you need anything else.
