### ISSUE TITLE
关于销售之后调整采购价格的问题

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1576]
一种是保价：就是客户手里的没有产品卖完，给客户调价，同时供应商给我司调价
 另一种就是返利 供应商对于每个产品 有销售回扣 这俩种情况都还好处理  
第三种客户手里没有卖完的不给保价 但是要找供应商要保价
这三种情况，在gooderp是否能处理

**Comment by GoodERPJeff** [comment]
没看懂。。。。举个详细的例子吧。按issue格式，操作步骤，运行结果，预期结果。。

**Comment by lonelyleaves** [comment]
首先采购入库10套，单价20.然后销售了3套，零售价50
现在供应商说要调整成本加，前面10套都改成22
现在供应商这边的账单能否处理？能否做一个销售/采购调价单用于调整价格？

**Comment by GoodERPJeff** [comment]
业务发生后修改成交价格，这个不是标准流程需求，无法支持。
