### ISSUE TITLE
销售采购的出入库单的结算可以选择结算的单据行

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1586]
销售/采购的出入库单有个成交金额，有个结算状态，但是查看不了收付款的单据，建议增加关联

**Comment by GoodERPJeff** [comment]
收款和发货不一定一一对应，所以这个关联加不上

按行结算涉及到整个结算单数据结构和与收发货单关联的逻辑，这个无法修改。
