### ISSUE TITLE
关于退货退款的单据显示问题

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1587]
操作系统及版本:
----
重现问题的步骤:
----
1.新建1张退单，数量1，单价100，并确认入库

2.创建1张付款单，金额是-100，退款给客户，并审核

当前结果:销售单据显示已收金额-100

期望的结果:如果是退货，已收金额变成已退金额，反向为正数

**Comment by GoodERPJeff** [comment]
类型是退货的销售订单上的已收金额是显示负数的，表示这笔订单是退给客户款的。
这样方便统计回款 正常销售回款  - 退货退款
所以这个问题暂时不做修改。
