### ISSUE TITLE
请问如何在群晖上部署Gooderp？

### ISSUE THREAD

**Issue by starboykm** [osbzr/gooderp_addons#1599]
操作系统及版本:
----群晖NAS
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by GoodERPJeff** [comment]
绿色版copy进去看能否运行

**Comment by starboykm** [comment]
Linux的绿色版？

**Comment by GoodERPJeff** [comment]
请在论坛 best.gooderp.org 上提问

**Comment by starboykm** [comment]
论坛上账号一直注册不了，我才来这里问的

**Comment by lonelyleaves** [comment]
相当于在linux安装 可以查下linux的安装方法
