### ISSUE TITLE
委外加工单中如何录入委外产生的废品

### ISSUE THREAD

**Issue by baoding-fenshuajiang** [osbzr/gooderp_addons#1604]
操作系统及版本:
----
重现问题的步骤:
       1.  通过委外加工单委外发料100件。
        2.  实际返回98件合格品，2件废品

当前结果:
       在委外加工单中没找到录入废品的入口

期望的结果:
      在委外加工单中有录入废品的入口

**Comment by GoodERPJeff** [comment]
期望的结果:
在委外加工单中有录入废品的入口

这个需求太模糊了，需要说明要在界面上哪个位置增加什么字段来实现这个功能。不具体的需求程序员如何实现呢？

**Comment by GoodERPJeff** [comment]
实现方案：
1、在公司上增加字段，wh_scrap_id（废品库），many2one到warehouse对象。
2、在 wh_move_line 上增加字段 scrap（报废） , boolean 类型，将其显示在委外加工单、组装单、拆卸单的line_in_ids 列表上
3、在单据成品入库的 approve_order 方法 order.line_in_ids.action_done()  # 完成成品入库 后，生成从调入仓库 到 废品库 的收获行上标记了报废的产品和数量的移库单并审核。

**Comment by GoodERPJeff** [comment]
开发完成，已合并，请测试一下
