### ISSUE TITLE
关于启用批次号唯一的产品的价格调整

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1606]
1：从供应商处采购了一批产品，数量是10，批次号分别为A001-A010
2：将这批产品全部卖给客户，出库无库存
3：现供应商调整产品价格，只要这些产品没有销售出去，可以凭产品照片给客户调整产品的价格

问题：A001-A010都已经销售给客户了，是分别给客户调整价格，做了一退一出，因为调整周期很长，供应商那边是一次性调整，就导致这些产品已经不在公司的库存，但是没有办法通过一退一进找供应商调整价格

不完善的方法：如果通过其他入库单先入库，会提示批次号重复，此路不通

请问：这种情况怎么处理

**Comment by GoodERPJeff** [comment]
调整价格不要做一退一出。数量上没有变化的事情不要虚拟出来，麻烦是自己创造的。

买卖已结束，价格调整作为其他业务收支录入，金额线下统计，事由单据上备注。
