### ISSUE TITLE
入库单和出库单，反审核，造成相关供应商和客户的所有付款单和收款单都消失了

### ISSUE THREAD

**Issue by jkhu99** [osbzr/gooderp_addons#1608]
操作系统及版本:
----
重现问题的步骤:
----
1. 针对供应商A，入库单1、入库单2、入库单3，录入相关付款单1、2、3；

2. 反审核入库单1，付款单1、2、3都消失了

3.

...

当前结果:
----

截图:

期望的结果: 不相关的付款单和收款单，不应消失，另外，反审核时是否应加入提示哪些单据会消失。
----

**Comment by Judystudy** [comment]
我这里没有重现。您那边是怎么出现的，有没有修改过代码？

**Comment by Judystudy** [comment]
重现步骤如下：先做3个入库单，然后相应的做3个付款单，不删除未核销的结算单，反审核其中一个入库单，这3个付款单就都消失了。
已修复，付款单审核时，把付款单源单行中本次付款为 0 的记录删除
