### ISSUE TITLE
建议：其他收入/其他支出单

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1614]
gooderp现在的其他收支单直接选择了付款方式，相当于做单的时候，收支已同时完成

正常应该是先做单，单据打印以后，签字之后才会领款或者付款，建议其他收支单走应收应付

**Comment by GoodERPJeff** [comment]
资金模块里只有结算单是管理应收应付的，其他收支是对收付款的补充，针对现金银行账户的增减进行记账。
