### ISSUE TITLE
权限冲突——无法显示采购入库单

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1617]
操作系统及版本:
----Ubuntu源码安装    版本是12月21日安装的github上的版本
重现问题的步骤:
----
1. 进入非Administrator账户（Adminstrator账户没有这个问题）

2.权限设置——勾选采购和仓库的所有权限

3.无法显示采购入库单

4.如果不勾选仓库权限则可以正常显示采购入库单，但看不到仓库模块

...

当前结果:
----

截图:

![image](https://user-images.githubusercontent.com/10705547/34442304-3c6b166a-ecfc-11e7-8d9d-2614d47fb027.png)

![image](https://user-images.githubusercontent.com/10705547/34442323-5eac15bc-ecfc-11e7-8db9-18b0d9b77fdf.png)

![image](https://user-images.githubusercontent.com/10705547/34442371-9b355c14-ecfc-11e7-808a-47f848289424.png)

期望的结果:
----

**Comment by zhhangtaao** [comment]
另外发现组装单也无法显示，具体冲突的权限没有具体测试。

**Comment by GoodERPJeff** [comment]
仓库-设置-仓库

在对应仓库的库管上选择对应用户
