### ISSUE TITLE
既是客户又是供应商的业务伙伴，在供应商 tree 视图点击 查看对账单 放大镜，显示的是客户对账单，存在 bug

### ISSUE THREAD

**Issue by Judystudy** [osbzr/gooderp_addons#1619]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:
![o_mk 5z1 nszglhpv9w sjo](https://user-images.githubusercontent.com/15152106/34472943-3603c242-efa7-11e7-85fa-85ca0920f98e.png)

期望的结果:
----

**Comment by GoodERPJeff** [comment]
已修复
