### ISSUE TITLE
借贷不平的Bug

### ISSUE THREAD

**Issue by starboykm** [osbzr/gooderp_addons#1622]
为什么做月末结账的时候回出现借贷不平？凭证都是自动生成的。
![image](https://user-images.githubusercontent.com/34362347/34475258-3e90577c-efc5-11e7-9494-b04fe0a66bf0.png)

**Comment by GoodERPJeff** [comment]
不是不平，是为0

应该是成本结转有问题

**Comment by starboykm** [comment]
@GoodERPJeff 
但是我看了都是有数值的，没有为0的项。
请问结转上哪里出了问题？

**Comment by GoodERPJeff** [comment]
公司上的成本结转方法是什么？

**Comment by starboykm** [comment]
@GoodERPJeff 
成本结算方式在哪里设置？
![image](https://user-images.githubusercontent.com/34362347/34475409-d2078dbc-efc6-11e7-99ac-c224b521f099.png)

**Comment by GoodERPJeff** [comment]
存货计价方法

你要结账的这个月，没有出库只有入库是么？

**Comment by starboykm** [comment]
@GoodERPJeff 
存货计价方法是全月一次加权平均
![image](https://user-images.githubusercontent.com/34362347/34476144-4ea1d3f8-efc9-11e7-96dc-a86d74e4e2cb.png)


我发现会随机的商品出现问题，而且不仅仅是库存商品，在组装单上的原材料也会。全部都有进出项的。

**Comment by GoodERPJeff** [comment]
https://github.com/osbzr/gooderp_addons/blob/master/finance/models/issue_cost_wizard.py#L182

比较一下这个脚本。我猜你用的不是最新版代码

**Comment by starboykm** [comment]
@GoodERPJeff 
![image](https://user-images.githubusercontent.com/34362347/34476490-34e57124-efcc-11e7-9e2b-daa10c30f4af.png)


好像还真不是。
我是12月从官网首页下的绿色版。
Linux和windows都出现这个问题。

**Comment by starboykm** [comment]
@GoodERPJeff 
Windows绿色版我更新过一遍了，还是不是最新代码。
Linux绿色版要如何更新？

**Comment by GoodERPJeff** [comment]
windows绿色版的更新是点 升级.bat
linux绿色版的更新是进gooderp_addons目录去git pull

**Comment by starboykm** [comment]
@GoodERPJeff 
不好意思，能给个完整的git pull 命令吗？

**Comment by starboykm** [comment]
@GoodERPJeff 
![image](https://user-images.githubusercontent.com/34362347/34477163-a902fb02-efd2-11e7-8d2f-48094dde1098.png)

我升级了，但是这个文件还是8月14的，并没有更新

**Comment by starboykm** [comment]
@GoodERPJeff Any idea？

**Comment by GoodERPJeff** [comment]
升级不成功肯定有报错的啊。你不会看报错？

或者淘宝交年费购买支持服务进QQ群我们会帮你看。

**Comment by starboykm** [comment]
@GoodERPJeff 
![image](https://user-images.githubusercontent.com/34362347/34508656-ccf25652-f07c-11e7-8d43-426de01d2078.png)

更新显示已经up to date。没有报错

**Comment by starboykm** [comment]
@GoodERPJeff 

不好意思，一直麻烦你。

我reset --hard 升级成功了
但是原来的数据库出现这个问题：

![image](https://user-images.githubusercontent.com/34362347/34509444-e5b1bfe0-f084-11e7-939c-e1892abb182e.png)


我更新Base模块，就彻底崩溃了
![image](https://user-images.githubusercontent.com/34362347/34509527-e688efd2-f085-11e7-9a29-619e94264bd4.png)

服务界面没有任何错误信息

![image](https://user-images.githubusercontent.com/34362347/34509534-f3786812-f085-11e7-9465-d4abcdd9485c.png)

**Comment by GoodERPJeff** [comment]
log目录下有gooderp.log文件，看一下有什么报错

**Comment by GoodERPJeff** [comment]
欢迎加入GoodERP应用和开发，群号码：530326001

**Comment by starboykm** [comment]
`2018-01-03 14:07:20,961 14640 ERROR asuliving werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\FACSYSYSYS\winruntime\python\lib\site-packages\werkzeug\serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "D:\FACSYSYSYS\winruntime\python\lib\site-packages\werkzeug\serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "D:\FACSYSYSYS\openobject\odoo\service\server.py", line 246, in app
    return self.app(e, s)
  File "D:\FACSYSYSYS\openobject\odoo\service\wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "D:\FACSYSYSYS\openobject\odoo\service\wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "D:\FACSYSYSYS\openobject\odoo\http.py", line 1308, in __call__
    return self.dispatch(environ, start_response)
  File "D:\FACSYSYSYS\openobject\odoo\http.py", line 1282, in __call__
    return self.app(environ, start_wrapped)
  File "D:\FACSYSYSYS\winruntime\python\lib\site-packages\werkzeug\wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "D:\FACSYSYSYS\openobject\odoo\http.py", line 1464, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\FACSYSYSYS\openobject\odoo\__init__.py", line 52, in registry
    return modules.registry.Registry(database_name)
  File "D:\FACSYSYSYS\openobject\odoo\modules\registry.py", line 59, in __new__
    return cls.new(db_name)
  File "D:\FACSYSYSYS\openobject\odoo\modules\registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\FACSYSYSYS\openobject\odoo\modules\loading.py", line 335, in load_modules
    force, status, report, loaded_modules, update_module)
  File "D:\FACSYSYSYS\openobject\odoo\modules\loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "D:\FACSYSYSYS\openobject\odoo\modules\loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "D:\FACSYSYSYS\openobject\odoo\modules\loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "D:\FACSYSYSYS\openobject\odoo\tools\convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "D:\FACSYSYSYS\openobject\odoo\tools\convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "D:\FACSYSYSYS\openobject\odoo\tools\convert.py", line 796, in parse
    self.parse(rec, mode)
  File "D:\FACSYSYSYS\openobject\odoo\tools\convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "D:\FACSYSYSYS\openobject\odoo\tools\convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "D:\FACSYSYSYS\openobject\odoo\addons\base\ir\ir_model.py", line 1190, in _update
    record.write(values)
  File "D:\FACSYSYSYS\openobject\odoo\addons\base\ir\ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "D:\FACSYSYSYS\openobject\odoo\models.py", line 3568, in write
    self._fields[key].determine_inverse(self)
  File "D:\FACSYSYSYS\openobject\odoo\fields.py", line 1041, in determine_inverse
    getattr(records, self.inverse)()
  File "D:\FACSYSYSYS\openobject\odoo\addons\base\ir\ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "D:\FACSYSYSYS\openobject\odoo\addons\base\ir\ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "D:\FACSYSYSYS\openobject\odoo\models.py", line 3560, in write
    self._write(old_vals)
  File "D:\FACSYSYSYS\openobject\odoo\models.py", line 3711, in _write
    self._validate_fields(vals)
  File "D:\FACSYSYSYS\openobject\odoo\models.py", line 1083, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "constraint \u68c0\u67e5\u9519\u8bef

\u5143\u7d20 '<button name="voucher_draft">' \u5728\u7236\u89c6\u56fe\u4e2d\u6ca1\u6709\u627e\u5230

\u9519\u8bef\u7684\u4e0a\u4e0b\u6587:
\u89c6\u56fe `create.tempalte.voucher.form`
[view_id: 377, xml_id: finance.create_tempalte_voucher_form, model: voucher, parent_id: 352]
None" while parsing file:/d:/facsysysys/gooderp_addons/finance/views/finance_view.xml:29, near
<record id="voucher_form" model="ir.ui.view">
            <field name="name">voucher.form</field>
            <field name="model">voucher</field>
            <field name="arch" type="xml">
                <form string="&#20250;&#35745;&#20973;&#35777;">
	                <header>
	                	<button name="voucher_done" states="draft" string="&#23457;&#26680;" type="object" class="oe_highlight"/>
                        <button name="voucher_can_be_draft" states="done" string="&#21453;&#23457;&#26680;" type="object"/>
                        <button name="action_cancel" states="draft" string="&#20316;&#24223;" type="object"/>
	                    <field name="state" widget="statusbar" readonly="1"/>
	                </header>
                    <sheet>
                        <group>
                            <group>
                                <field name="document_word_id" widget="selection" readonly="1"/>
                                <field name="name" readonly="1" style="width: 30%%"/>
                                <field name="ref" groups="base.group_no_one"/>
                            </group>
                            <group>
                                <field name="date"/>
                                <field name="period_id" options="{'no_open':True,'no_create':True}"/>
                                <field name="att_count"/>
                                <field name="is_init" invisible="1"/>
                            </group>
                        </group>
                        <field name="line_ids" context="{'line_ids':line_ids}">
                            <tree editable="bottom">
                                <field name="name"/>
                                <field name="account_id" options="{'no_create': True}" context="{'show_balance':True}"/>
                                <field name="partner_id" options="{'no_open': True, 'no_create': True}" domain="[('name','=',False)]"/>
                                <field name="goods_id" groups="finance.group_account_goods" domain="[('name','=',False)]"/>
                                <field name="goods_qty" groups="finance.group_account_goods"/>
                                <field name="auxiliary_id" domain="[('name','=',False)]"/>
                                <field name="currency_id" options="{'no_create': True}" groups="finance.group_multi_currency"/>
                                <field name="currency_amount" sum="&#22806;&#24065;&#21512;&#35745;" groups="finance.group_multi_currency"/>
                                <field name="rate_silent" groups="finance.group_multi_currency"/>
                                <field name="debit" sum="&#20511;&#26041;&#21512;&#35745;"/>
                                <field name="credit" sum="&#36151;&#26041;&#21512;&#35745;"/>
                                <field name="init_obj" invisible="1"/>
                            </tree>
                        </field>
                        <group>
                            <field name="amount_text" widget="num_to_china"/>
                        </group>
                    </sheet>
                    <div class="oe_chatter">
	                    <field name="message_follower_ids" widget="mail_followers"/>
                        <field name="_to_approver_ids" widget="goodprocess" readonly="1"/>
	                    <field name="message_ids" widget="mail_thread"/>
	                </div>
                </form>
            </field>
        </record>`


这个是刚才生成的Log。
@GoodERPJeff 请问那个是QQ群吗？

**Comment by GoodERPJeff** [comment]
是qq群
