### ISSUE TITLE
采购入库单 单位成本计算错误

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1623]
操作系统及版本:
----
Ubuntu 
重现问题的步骤:
----
1.
新建采购入库单
2.
修改商品单价，触发计算单位成本
3.
查看商品单位成本
...

当前结果:
----

截图:
![image](https://user-images.githubusercontent.com/10705547/34530064-f28feebc-f0e8-11e7-952a-6dcda505aa9a.png)

![image](https://user-images.githubusercontent.com/10705547/34530112-156970de-f0e9-11e7-997a-1c9ae1575f55.png)

期望的结果:
----

分析记录   应该和这次提交有关  ：

https://github.com/osbzr/gooderp_addons/commit/de696b458e947f0a78f1986454c3f43c026018a0

**Comment by GoodERPJeff** [comment]
已修复
