### ISSUE TITLE
请问安装文档在哪里？

### ISSUE THREAD

**Issue by jackiilong** [osbzr/gooderp_addons#1642]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by Judystudy** [comment]
这是我们用户手册地址：https://www.kancloud.cn/osbzr/gooderp_user_manual/295107

**Comment by GoodERPJeff** [comment]
http://best.gooderp.org/t/gooderp
