### ISSUE TITLE
补货申请无法删除具体条目

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1647]
操作系统及版本:
----
重现问题的步骤:
----
1.非管理员用户创建补货申请

2.选择编辑编辑补货申请

3.

...

当前结果:
----
没有删除功能，补货条码无法删除；
只有Administrator才可以删除

截图:
![image](https://user-images.githubusercontent.com/10705547/37639177-50c28470-2c4b-11e8-8b49-4004968239e0.png)

期望的结果:
----
普通用户也可以删除条目

**Comment by GoodERPJeff** [comment]
其实权限csv里写了，连管理员用户都不应该删除这些行。

场景：
----

某产品建议补货数量 20 件，但审批者认为无需补（滞销品或老款），则在修改最低库存之前，这里可以修改申请补货数量为0
这样的历史记录可以看出人为决策的痕迹。
如果只是删除，谁会知道系统算出来的理应补货20这个记录呢？
不过程序应该检查一下申请补货数量为0的行不要生成采购单。。。

**Comment by GoodERPJeff** [comment]
其实权限csv里写了，连管理员用户都不应该删除这些行。

场景：
----

某产品建议补货数量 20 件，但审批者认为无需补（滞销品或老款），则在修改最低库存之前，这里可以修改申请补货数量为0
这样的历史记录可以看出人为决策的痕迹。
如果只是删除，谁会知道系统算出来的理应补货20这个记录呢？
不过程序应该检查一下申请补货数量为0的行不要生成采购单。。。

**Comment by zhhangtaao** [comment]
感谢回复，确实测试过补货申请填写0不会申请采购单
