### ISSUE TITLE
修改销货单地址，地址下拉列表有误的问题

### ISSUE THREAD

**Issue by arook** [osbzr/gooderp_addons#1651]
操作系统及版本:MacOS 10.13.3

重现问题的步骤:
----
1.新建若干个客户，每个客户新建若干个联系人；

2.新建销货单，选择客人，可以看到地址下拉列表是准确的，保存；

3.编辑销货单，点击地址，地址下拉列表是所有的地址列表；

4.选择其他的客户，再看地址列表，就正常了。

...

当前结果:
----
定义sell_order的时候，address_id定义有问题，应该加入限制domain进去

    address_id = fields.Many2one('partner.address', u'地址', states=READONLY_STATES,
                                 domain="[('partner_id', '=', partner_id)]",
                                 help=u'联系地址')

[代码地址](https://github.com/osbzr/gooderp_addons/blob/ce10a229083f9b75532bdd3654d18d4c571b41c4/sell/models/sell_order.py#L81)

截图:
￼
￼
![1522053132810](https://user-images.githubusercontent.com/385978/37895225-40bdc978-3113-11e8-8fbb-5265411a653a.jpg)
￼

期望的结果:
----

**Comment by luoguizhou** [comment]
@arook 不支持这种动态domain的写法
