### ISSUE TITLE
在不存在的期间创建和审核发货单，不会生成结算单和凭证，审核通过不报错

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1666]
操作系统及版本:
----
重现问题的步骤:
----
1.确认2018年5月期间不存在

2.新建发货单

3.审核

...

当前结果:
----
审核通过，但发货单上结算单和凭证两个字段均为空

截图:

期望的结果:
----
报错 期间不存在

**Comment by lonelyleaves** [comment]
经测试 发现情况不能复现，如果会计区间已经结账之后 不会出现在提示会计区间不存在单据状态变更的情况

**Comment by lonelyleaves** [comment]
经检查多个账套 
 每个月的第一个单据才会有一定的概率出现 但是多种情况测试都没有办法复现

**Comment by GoodERPJeff** [comment]
期间若不存在会自动创建，此issue已无效
