### ISSUE TITLE
结算帐户与业务伙伴币别不一致。 结算账户币别:CNY 业务伙伴币别:USD

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1669]
操作系统及版本:
----
重现问题的步骤:
----
1.结算帐户与业务伙伴币别不一致。
结算账户币别:CNY 业务伙伴币别:USD

...

当前结果:
----
如何处理这个报错

截图:

期望的结果:
----

**Comment by GoodERPJeff** [comment]
没明白啊，这是一句报错吧。

步骤是什么，预期结果是什么，实际结果是什么？

**Comment by lonelyleaves** [comment]
Gooderp的demo数据的WH/IN/00013，单据的本次成交金额等于本次付款金额，直接系统出现这个报错
