### ISSUE TITLE
组装单如果成品有多属性或者管理批次号无法使用

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1690]
操作系统及版本:
----
重现问题的步骤:
----
1.新建成品A，勾选管理批次，新建子件B，保存

2.新建物料清单，A=3B,保存

3.新建组装单，选择物料清单，输入批次号，保存

...

当前结果:
----
报错缺少入库明细

截图:

期望的结果:
----

**Comment by GoodERPJeff** [comment]
此时需要 勾选 专家模式 在成品行输入批次或者序列号
