### ISSUE TITLE
BOM line的数量默认值应该为1，并验证大于0

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1696]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by leangjia** [comment]
![bom](https://user-images.githubusercontent.com/5299151/38966787-85ed394c-43b6-11e8-9817-f410bb169eb3.png)同意默认值为1，方便录入；另外，在使用鼠标点击的情况下，默认值0.0，在输入数字后，后面的0.0也没变，就会造成不便。如改为默认值为1.0亦然。盼考虑更优输入方式。感谢！辛苦啦！

**Comment by leangjia** [comment]
附一例：jquery自动对焦全选
![default](https://user-images.githubusercontent.com/5299151/38967534-0bbc55dc-43ba-11e8-9765-f1087e24c229.png)

[test全选文字.zip](https://github.com/osbzr/gooderp_addons/files/1926400/test.zip)
