### ISSUE TITLE
任务模块工作记录做一个看板视图，方便员工在手机上记工时，今日看板增加图片显示

### ISSUE THREAD

**Issue by floraXiao** [osbzr/gooderp_addons#1710]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by GoodERPJeff** [comment]
重新实现

不是新增一个菜单，而是在今日的菜单里把工作记录行从列表改成看板
