### ISSUE TITLE
还有未汉化的 or 有待解决

### ISSUE THREAD

**Issue by leangjia** [osbzr/gooderp_addons#1728]
操作系统及版本:win2003 server 64bit+绿色版GoodERP 最新下载；
----
重现问题的步骤:
----
1.在仓库菜单->报表中的：呆滞料报表还有尚未汉化的 英文  or

2.

3.

...

当前结果:
----

截图:
![gooderp01](https://user-images.githubusercontent.com/5299151/39612314-daa44b48-4f90-11e8-8c47-faabd4997ecc.png)

期望的结果:
----

**Comment by leangjia** [comment]
更新到最新源码，or也还在。

**Comment by GoodERPJeff** [comment]
未重现
