### ISSUE TITLE
关于根据发票确认应收应付的bug

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1743]
如果开账的时候选择根据发票确认应收应付，则所有的结算单invoice都需要手工确认才会更新应收应付金额 

后因为其他原因需要关闭根据发票确认应收应付 发现一个问题，原来的结算单已经是已收/已付状态，现在全部变成未付款状态，收付款单上明细是已经全部核销

不完善的解决思路：导出收付款单的invoice的已核销金额，然后导入到invoice，发现已收/已付金额不能导入

期望的办法：修复这个按钮的功能，比如修改的时候不变更已经结算的单据

**Comment by lonelyleaves** [comment]
关于这个按钮 建议没有修复之前 大家不要随便变更公司上的参数

**Comment by GoodERPJeff** [comment]
请程序员重现一下这个问题

**Comment by floraXiao** [comment]
没有重现，跟落叶探讨可以关闭
