### ISSUE TITLE
组装单概率性出现“请输入凭证号”问题

### ISSUE THREAD

**Issue by starboykm** [osbzr/gooderp_addons#1751]
操作系统及版本:
----
重现问题的步骤:
----
1.在填写完组装单点发料的时候，会有概率弹出“请输入凭证号”的问题，无法继续。

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by starboykm** [comment]
@GoodERPJeff 问题找到了，如果全部都是来料，且没有入库成本的话，就会出现问题。

**Comment by lonelyleaves** [comment]
如果是代价格，供方是不会提供物料成本，加工方是做其他收入入库，成本是0，这样就会出现这种请输入入库凭证号的问题
如果可以 我觉得就用odoo的生产模块，其实也是够用，是否可以迁移？
