### ISSUE TITLE
版本更新——科目名称重复数据库无法升级

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1761]
操作系统及版本:
----
重现问题的步骤:
----
1.从旧版升级至最新版本

2.更新base模块

3.

...

当前结果:
----

base模块升级失败，无法访问。

截图:
![image](https://user-images.githubusercontent.com/10705547/40549488-25ca007e-606a-11e8-94de-a8441a01322d.png)

期望的结果:
----

## 原因猜测：
查看更新记录发现近期更新了科目的层级。
原数据库中已经存在很多科目，更新之后好像又将这些科目重新加入了一遍导致code重复无法升级。

**Comment by GoodERPJeff** [comment]
xml_id被改了，就会有这样的问题。我周末修复一下。

**Comment by GoodERPJeff** [comment]
已修复，请先在测试系统测试再升级生产系统
