### ISSUE TITLE
新建帐无法输入科目余额表期初

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1769]
我的理解启用日期是当前会计期间所在的月份可以进行科目余额表的输入

![image](https://user-images.githubusercontent.com/10705547/40606589-6e1126e8-6298-11e8-8b92-0f4e935e3bed.png)

操作系统及版本:
----
ubuntu  5月23日左右的版本
重现问题的步骤:
----
1.新建帐，输入科目余额表数据。
保证启用日期为当前会计期间。

2.可以输入本年累计的借方和贷方
![image](https://user-images.githubusercontent.com/10705547/40606767-013931cc-6299-11e8-9452-bd4da253235c.png)

3.点击保存，可以看到新增一条数据，但是数据总条数没变。
![image](https://user-images.githubusercontent.com/10705547/40606814-328106ec-6299-11e8-94b8-298a4e595ff4.png)

4.刷新页面后刚刚新增的数据消失
![image](https://user-images.githubusercontent.com/10705547/40606885-6027eae8-6299-11e8-8123-efaec7213c59.png)

...

当前结果:
----
科目余额表新增数据无法保存

截图:

期望的结果:

----

**Comment by jeffery9** [comment]
科目余额表 根据科目的记账情况 动态生成的， 原本的逻辑是：
 如果该期间 没有结账， 将已存在的该期间的科目余额表项目清除， 然后重新填充
 如果该期间是 关闭的， 将不会对 科目余额表项目进行 任何修改【 新建、更新】

修改时， 直接 在 余额表项目 上 修改字段值

所以， 调整 科目余额， 仅对 已经关闭的期间起作用

修改之后的逻辑
 如果该期间 没有结账， 将已存在的该期间的科目余额表项目清除， 然后重新填充
 如果该期间是 关闭的， 将不会对 科目余额表项目进行 任何修改【 新建、更新】，但是， 如果 有新增的科目， 则为  新增科目 建立科目余额表 项目。

为科目余额表项目 增加 调整余额 按钮， 使用 向导窗口进行调整

**Comment by zhhangtaao** [comment]
好的  更新到最新版确实多了调整余额按钮    非常感谢

**Comment by GoodERPJeff** [comment]
这个期初建账的逻辑应该修改一下了：

期初凭证应该包含建账期间的收入和费用科目本年累计数，不包含本年利润科目的科目余额。

这样建账期间结账后，就可以得到损益类科目的本年累计数，并通过调整本年累计功能获取资产负债表科目的年初数和本年累计数。
