### ISSUE TITLE
版本升级失败，提示其他应付款code重复

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1785]
操作系统及版本:
----
Ubuntu  6月1日最新版本
重现问题的步骤:
----
1.旧版本数据库升级至最新版

2.更新base模块

3.

...

当前结果:
----
`DETAIL:  Key (code)=(2241) already exists.
" while parsing /home/good/gooderp_addons/finance/data/finance_data.xml:648, near
<record id="small_business_chart2241" model="finance.account">
            <field name="code">2241</field>
            <field name="name">&#20854;&#20182;&#24212;&#20184;&#27454;</field>
            <field name="user_type" ref="base_debt"/>
            <field name="account_type">view</field>
            <field name="source">init</field>
            <field name="balance_directions">out</field>
        </record>`

截图:

![image](https://user-images.githubusercontent.com/10705547/40845307-e6189d6c-65e8-11e8-81b2-aeb2e9b23d9a.png)

期望的结果:
----

**Comment by GoodERPJeff** [comment]
sql 去更新一下code和name，升级好以后删掉吧
