### ISSUE TITLE
组装单添加商品后无法提取成本

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1831]
操作系统及版本:
----
重现问题的步骤:
----
1.新建组装单，添加任意子件

2.子件成本始终为0

3.单击发料之后才会出现成本

...

当前结果:
----

截图:

![image](https://user-images.githubusercontent.com/10705547/41590459-99e230b6-73e9-11e8-9153-8b0a2e93db7b.png)

期望的结果:
----
添加子件之后自动提取成本

**Comment by GoodERPJeff** [comment]
发料前无法确定这批实发物料的成本

**Comment by zhhangtaao** [comment]
如果成本核算方法为加权平均，
应该是可以知道出库成本的吧。就算没出库库存列表也有成本字段呀
