### ISSUE TITLE
从物料清单创建组装单，辅助数量不会更新BUG

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1835]
操作系统及版本:
----
重现问题的步骤:
----
1.创建物料清单，输入任意物料 数量输入100

2.创建组装单，选择物料清单

3.

...

当前结果:
----
辅助数量不会更新，始终为1，只有手动修改数量才会

截图:
![image](https://user-images.githubusercontent.com/10705547/41633779-097b055e-7473-11e8-97c0-5bed23bf3e8a.png)

期望的结果:
----
导入物料清单，更新辅助数量

**Comment by Judystudy** [comment]
测试，没有发现您说的问题。

**Comment by zhhangtaao** [comment]
我用的是6月15日的版本  之前版本确实没问题。。最近才出现的问题   我看提交历史有一次提交是默认数量修改为1    可以确认一下是不是这个提交影响的

**Comment by zhhangtaao** [comment]
已经升级到6月21日最新版了，这个问题依然存在。系统Ubuntu源码安装

**Comment by zhhangtaao** [comment]
非常感谢~！
