### ISSUE TITLE
月末结账，多出一条发出成本的会计凭证

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1844]
操作系统及版本:
----
ubuntu    6月21日最新版本
重现问题的步骤:
----
1.组装单发料——成品入库

2.销售发货单

3.月末结账

...

当前结果:
----
月末结账时多生成了一条发出成本的会计凭证。这样的话本月的原材料和生产成本发生额就都为0了，与实际不符。

截图:

![image](https://user-images.githubusercontent.com/10705547/41825840-213fb670-7857-11e8-951d-279cb7df6a2d.png)

期望的结果:
----

**Comment by zhhangtaao** [comment]
我用最新的程序新建数据库  模拟出了同样的问题

步骤如下：

## 创建数据库 设置启用日期 为3月份
![1](https://user-images.githubusercontent.com/10705547/41883552-b80f5766-7921-11e8-9a8e-f0d2af28c1db.png)

## 其他入库 数量10 单价 10
![image](https://user-images.githubusercontent.com/10705547/41883593-eded59f0-7921-11e8-9e6d-4c7ca5b21842.png)

## 销售发货 数量1 单价100

销售发货之后月末结账，生产会计凭证没有问题
![2](https://user-images.githubusercontent.com/10705547/41883651-2ce1ba2a-7922-11e8-9a47-87a3a19f33e9.png)

## 4月份 销售发货 数量1 单价100 会计凭证同样没有问题

## 5月份 没进行任何操作直接结账

## 6月份 销售发货 数量1 单价100  问题出现
结账之后发出成本截图
![3](https://user-images.githubusercontent.com/10705547/41883688-66741e04-7922-11e8-8df2-b419bf43034d.png)

会计期间截图
![4](https://user-images.githubusercontent.com/10705547/41883705-7ac94c6c-7922-11e8-889e-0d1d20ee0a63.png)

会计凭证截图
![image](https://user-images.githubusercontent.com/10705547/41883721-94d4cc3a-7922-11e8-9b51-474c2516ba46.png)

**Comment by leangjia** [comment]
看着头晕，帮顶一下

**Comment by leangjia** [comment]
没有看到设置启用日期 为3月份
如下图：
![gooderp02](https://user-images.githubusercontent.com/5299151/41884673-f978ab6c-7926-11e8-9020-60c9203e97a2.png)

**Comment by zhhangtaao** [comment]
激活开发者模式
![image](https://user-images.githubusercontent.com/10705547/41884706-19ff5142-7927-11e8-905e-62dc5fa601a5.png)

**Comment by leangjia** [comment]
销售发货 数量1 单价100

销售发货之后月末结账，生产会计凭证没有问题

这里我的会计凭证跟你的不太一样：
![gooderp03](https://user-images.githubusercontent.com/5299151/41884898-11fbe72a-7928-11e8-831c-19d8f13c2800.png)

**Comment by zhhangtaao** [comment]
过程很长  上来就有问题的话就好解决了

**Comment by zhhangtaao** [comment]
[testnew_2018-06-26_02-09-43.zip](https://github.com/osbzr/gooderp_addons/files/2135306/testnew_2018-06-26_02-09-43.zip)
这个是上门这些操作的数据库

**Comment by zhhangtaao** [comment]
找到问题了
![image](https://user-images.githubusercontent.com/10705547/41894107-7c1403fe-7950-11e8-8602-00c08e9ee735.png)

发出成本需要查找该商品上一期间的期末数据，上一期间是根据期间的ID来判断顺序的。如果期间建立不是按顺序的就无法取得上一期间的期末数据。
