### ISSUE TITLE
低值商品出库时借贷方不平、无法确认！

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1847]
操作系统及版本:
----
6月25日 最新版本
重现问题的步骤:
----
1.
低值产品较多，数量较大时，创建组装单发料。
2.

3.

...

当前结果:
----
借贷方不平、无法确认！

截图:
![image](https://user-images.githubusercontent.com/10705547/41897677-8da24f90-795a-11e8-9338-4675bac0d7c4.png)

期望的结果:
----

**Comment by zhhangtaao** [comment]
精度位数设定
![image](https://user-images.githubusercontent.com/10705547/42149427-a3e284e8-7e08-11e8-9ca3-724663921dbc.png)


## 问题分析：
问题产生在组装单对应的会计凭证上（出库凭证），会计凭证借方和贷方不平

出库凭证的贷方是原材料明细  成本 × 数量取两位小数 再求和
而借方应该是  成本 × 数量 求和之后再取的两位小数  

导致最后计算的结果不同 

建议借方价格计算方法修改为 成本 × 数量取两位小数 再求和 

注：Amount 精度设置为2

**Comment by floraXiao** [comment]
把Price和Amount精度设置成相同的即可

**Comment by zhhangtaao** [comment]
经测试问题修复，非常感谢
