### ISSUE TITLE
已有核销单的固定资产不允许反审核

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1852]
操作系统及版本:
----
重现问题的步骤:
----
1.创建固定资产

2.核销

3.反审核固定资产

...

当前结果:
----
可以反审核固定资产，导致核销单金额对不上，无法反审核

截图:
![image](https://user-images.githubusercontent.com/10705547/42067970-c21103b6-7b7b-11e8-8e55-b7c88842fc5b.png)

期望的结果:
----
已有核销金额的固定资产不允许删除  或者可以删除核销金额不相等的核销单

**Comment by GoodERPJeff** [comment]
此需求可修改为：

已核销金额不为0的结算单不可以反审核。

**Comment by GoodERPJeff** [comment]
结算单反审核没有直接的界面，都是被其他流程调用的。所以“已核销金额不为0的结算单不可以反审核。”这个需求不对。
