### ISSUE TITLE
采购入库后，商品上的成本不会更新，依然为0

### ISSUE THREAD

**Issue by zhhangtaao** [osbzr/gooderp_addons#1853]
操作系统及版本:
----
重现问题的步骤:
----
1.新建商品

2.采购入库单

3.

...

当前结果:
----
库存余额表里已经可以看到商品以及成本，商品里面看不到成本。

截图:
![image](https://user-images.githubusercontent.com/10705547/42068434-8fa0ceb8-7b7e-11e8-8a8e-7f2f198b6483.png)
![image](https://user-images.githubusercontent.com/10705547/42068442-a0c9b9de-7b7e-11e8-9406-4df2e697905d.png)

期望的结果:
----
根据入库单位成本填充

**Comment by GoodERPJeff** [comment]
入库成本是一次性的，商品上的成本是个计划数字，反向填充合理么？

**Comment by zhhangtaao** [comment]
记得之前的老版本是可以自动填充的，我以为这个功能失效了，如果一直都是不填充的就没关系。看成本就到库存余额表里看就OK

**Comment by GoodERPJeff** [comment]
已确认无需修改
