### ISSUE TITLE
新模块 sell_to_buy 根据销售订单创建采购订单

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1857]
0、模块依赖sell 和 buy
1、销售订单行上增加隐藏字段 buy_line_id 和 已采购字段
2、采购订单上增加按钮，【根据销售订单生成】，增加字段，销售订单
2、弹出窗口，按销售订单分组，显示所有已采购为否的销售订单行
3、一次只能勾选一张销售订单的行
4、勾选后 点击【生成】按钮，将所选订单行信息复制到销售订单（价格取自商品的成本字段或者供应商供货价格）

**Comment by floraXiao** [comment]
销售订单行上增加隐藏字段 buy_line_id 
对于这个不理解，是否应该为采购订单行上增加隐藏字段sell_line_id？
