### ISSUE TITLE
客户和供应商界面上增加字段：付款条件

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#1859]
字符串类型

related 显示在结算单上，到期日后面，只读

字段用来根据与业务伙伴约定的付款条件和开票的日期人工计算到期日

**Comment by lonelyleaves** [comment]
还要考虑客户/供应商的分类，不同的客户 给个基础时间，比如一类客户就是默认的到期日期，二类又增加多少天

**Comment by GoodERPJeff** [comment]
已经用落叶的信用天数字段解决
