### ISSUE TITLE
收/付款单切换往来单位，如果新切换的往来单位没有与之对应的结算单，则付款核销行不刷新

### ISSUE THREAD

**Issue by znb1992** [osbzr/gooderp_addons#1861]
操作系统及版本:
----GoodERP-2018-07-03

问题详细描述：
----1. 收/付款单切换往来单位，如果新切换的往来单位没有与之对应的结算单，则付/付款核销行不刷新；新切换来往单位有与之对应的结算单，则收/付款单核销行是刷新的。
      
      2.  如果新切换的往来单位没有与之对应的结算单，则付/付款核销行不刷新，然而该来往单位没有真实结算单时，点击收付款单的【保存】，甚至【确认】按钮也不会刷新核销行，而且错误的付款来往单位选择竟然可以核销真实的结算单。

重现问题的步骤:
----
1.  我们设置三个供应商(A, B, C)。并通过采购下单，并确认收货入库的方式，完成其中两个供应商（A和B）的采购过程，生成未核销的结算单两张，剩下的一个供应商（C）不参与采购，并保证再此之前三个供应商没有未核销的结算单。

2. (1) 创建付款单，来往单位选择：A,  发现：核销行刷新出A所对应的结算单。
    (2) 切换往来单位，来往单位切换：B,  发现：核销行刷新出B所对应的结算单，没有问题。
    (3) 切换往来单位，来往单位切换：C,  发现：核销行不刷新，仍保持B所对应的核销行不变，我们知道此时C对应的核销行为空才是对的。

3. （1） 在2（3）的基础上点击付款单的【保存】按钮依旧不会刷新核销行。
   （2） 在保存的基础上，点击付款单【确认】，也不会刷新核销行，更为严重的是，核销行中的结算单被核销掉了。
 

...

当前结果:
----   付款单往来单位切换不会刷新，错位的核销行，可以被真实核销。

截图:
1.  供应商A，采购下单，等分两个批次完成入库确认，生成如下结算单：
![default](https://user-images.githubusercontent.com/20330103/42193841-99bf0536-7ea3-11e8-8ef1-655765dddf65.png)
2. 供应商B，采购下单，一次性完成入库确认，生成如下结算单：
![default](https://user-images.githubusercontent.com/20330103/42193873-cc1713b6-7ea3-11e8-99b5-2f670d6cd611.png)
3. 创建付款单，来往单位选择：A,  发现：核销行刷新出A所对应的结算单。
![default](https://user-images.githubusercontent.com/20330103/42194253-9f42b7f8-7ea5-11e8-8282-78908aa3a843.png)
4.切换往来单位，来往单位切换：B,  发现：核销行刷新出B所对应的结算单，没有问题。
![default](https://user-images.githubusercontent.com/20330103/42194268-af0cc34a-7ea5-11e8-804c-935ce0535187.png)
5.切换往来单位，来往单位切换：C,  发现：核销行不刷新，仍保持B所对应的核销行不变，我们知道此时C对应的核销行为空才是对的。
![default](https://user-images.githubusercontent.com/20330103/42193984-43f9b15e-7ea4-11e8-8858-409f23ba3808.png)
6. 基础上点击付款单的【保存】按钮依旧不会刷新核销行，输入结算金额，点【确认】。
![default](https://user-images.githubusercontent.com/20330103/42194077-c1606e3a-7ea4-11e8-8f37-28e2859cfd9e.png)
7. 付款单往来单位切换不会刷新，错位的核销行，可以被真实核销。
![default](https://user-images.githubusercontent.com/20330103/42194060-aa3f5e96-7ea4-11e8-90fe-709cafa1c054.png)

期望的结果:
----收/付款单每次切换往来单位，都需要刷新一次核销行，保证往来单位与核销行不会因刷新错位

**Comment by yangzhibing** [comment]
同样的问题
