### ISSUE TITLE
关于批次、属性权限控制问题

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1865]
操作系统及版本: Ubuntu14.04+gooderp
----
如果商品启用批次/属性，但是操作的人员没有批次权限，会导致一些异常问题
1、其他入库单可以添加，但是打印会失败报js错误，不会报属性/批次问题
2、入库的产品勾选了批次，但是因为操作的人员没有批次，导致这个产品进出不会有批次信息

期望的结果:
对产品的多属性、批次管理，和权限无关，不管有没有权限，商品设置了多属性或者批次就一定要有相关的信息，可以报错或者单据不允许审核都可以

**Comment by floraXiao** [comment]
问题1没重现：商品勾上管理批号，操作人员无批号权限，他创建其他入库单，添加明细行，打印没有报错
