### ISSUE TITLE
已经使用的记录不允许删除

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#20]
检查所有关联字段的ondelete属性

**Comment by JasonAxesen** [comment]
many2one 字段上加ondelete='restrict'(不能删除原纪录)'set null'(删除原纪录将本条记录置空)'cascade'（删除原纪录将本条记录删除）

**Comment by floraXiao** [comment]
[ADD]增加测试用例及实现：删除采购入库单时可以删除关联的入库单行 #128
