### ISSUE TITLE
仓库报表成本统计有问题，成本一直为0

### ISSUE THREAD

**Issue by yanshaozhi** [osbzr/gooderp_addons#249]
仓库->报表->库存余额表  成本一直为零，不知道是使用问题还是真实bug

**Comment by OpenERPJeff** [comment]
![image](https://cloud.githubusercontent.com/assets/1857069/15038102/8047e034-12d3-11e6-9885-10c52e6056f3.png)

是不是入库时没有输入单价？

**Comment by yanshaozhi** [comment]
是通过采购单入库单，入库的，有单价。

**Comment by OpenERPJeff** [comment]
未能重现
