### ISSUE TITLE
其他收入和其他支出可选择服务

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#317]
操作系统及版本: all
----
重现问题的步骤:
----
1. 新建其他收入、其他支出单
2. 只能直接选择收入支出类别，不能再详细选定具体服务产品
3.企业运营过程中的服务采购（如erp实施）和销售（如保养合同）没有统一的地方输入
...

当前结果:
----
其他收入和其他支出只能管理到类别级别

截图:

期望的结果:
----
能够在其他收入、其他支出上选择服务，并带出服务对应的收支类别，以便管理非主营业务非库存管理商品的采购和销售记录。

1- 新建组，管理服务，针对这个组显示 服务 菜单和 其他收支单上的服务字段

2- 新建 服务 对象，字段有 名称、收入类别、支出类别、价格

3- 在其他收入单和其他支出单上增加 服务 字段，选择这个字段后带出服务对应的分类和价格。

**Comment by floraXiao** [comment]
已完成
