### ISSUE TITLE
隐藏会计凭证行上的商品字段

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#324]
操作系统及版本:所有
----
重现问题的步骤:
----
1. 新建会计凭证
2.行上的商品字段不知道什么作用
...

当前结果:
----
回为没开发材料明细账的报表,凭证行上的商品字段暂是没有作用

截图:

期望的结果:
----
增加一个新的用户组,叫凭证行上的商品,商品字段仅对这个组可见

**Comment by JasonAxesen** [comment]
已修改
