### ISSUE TITLE
会计期间所有字段只读

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#325]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
会计年度、会计月份和已结账字段在已结账和未结账状态下都可修改

截图:

期望的结果:
----
在未记账的状态下会计年度和会计月份可修改，已结账不可修改；在已结账状态下都是只读状态。

**Comment by JasonAxesen** [comment]
已修改
