### ISSUE TITLE
科目明细账凭证明细行输出的余额不对

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#327]
操作系统及版本: all
----
重现问题的步骤:
----
1. 进入会计-账簿-科目明细账 菜单
2.打印一个有凭证的科目的明细账
3.
...

当前结果:
----
有凭证编号的余额列数值不对，简单的借方减贷方了

截图:

![image](https://cloud.githubusercontent.com/assets/1857069/15665006/daaa8998-273a-11e6-95a6-1fb3b73c85e3.png)

期望的结果:
----

有凭证编号的明细行的余额应该是上一笔凭证的余额 + 本行的借 - 本行 的贷，再根据借贷方向取绝对值

第三行应为 0

第五行应为2370

第六行应为2398.6

**Comment by OpenERPJeff** [comment]
![image](https://cloud.githubusercontent.com/assets/1857069/15800092/17afa682-2aa3-11e6-9338-d5a9a5a615b3.png)

跨月的没考虑前一个期间的余额

**Comment by yunkuaiji** [comment]
可以close了
