### ISSUE TITLE
系统参数里的本年利润科目和未分配利润科目应设置默认值

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#330]
操作系统及版本:
重现问题的步骤:
通过菜单：“配置-->高级配置-->系统参数”
当前结果:
本年利润科目和未分配利润科目字段的值为空
期望的结果:
本年利润科目默认为“本年利润”，未分配利润科目科目为“利润分配-未分配利润”。
![gooderp](https://cloud.githubusercontent.com/assets/7471985/15693195/fd4c6576-27c5-11e6-8a3e-e4143751fe85.png)

**Comment by JasonAxesen** [comment]
已修改
