### ISSUE TITLE
资产负债表模板里年初余额计算公式应改为计算公式

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#333]
操作系统及版本:
----
重现问题的步骤:
----
【会计】【资产负债表模板】标题
...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/18207232/15699880/0ed709c6-2803-11e6-9c7d-cb2bcfc35fe9.png)

期望的结果:
----
年初余额计算公式改为计算公式

**Comment by floraXiao** [comment]
已修改
