### ISSUE TITLE
“首页” 中的采购入库单、销售发货单等无默认图片。

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#335]
操作系统及版本:
----
重现问题的步骤:
点击“首页菜单”
期望的结果:
有默认图片，看起来能舒服些。

**Comment by gilbert-yuan** [comment]
更换实现方式,让页面看起来更舒坦了点.(取消图片的)

**Comment by OpenERPJeff** [comment]
https://github.com/osbzr/gooderp_addons/commit/9b8b04f9e9b2a191d9cb1b9826dc9fa98c695aab
