### ISSUE TITLE
在商品窗体中新建的供应商，不能通过供应商菜单显示，而点击客户菜单才显示。

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#336]
重现问题的步骤:
通过菜单 配置-->基础资料-->商品，新建一个商品，在供应商一节通过下拉菜单选择新建，然后保存。
当前结果:
通过菜单  配置-->基础资料-->供应商，此供应商不能显示。（通过菜单  配置-->基础资料-->客户，发现显示在这里了）

截图:

期望的结果:
在产品窗体新建的供应商，能通过菜单  配置-->基础资料-->供应商 显示。

**Comment by floraXiao** [comment]
已修改
