### ISSUE TITLE
每个商品只能选择一个供应商，希望能选择多个。

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#338]

**Comment by OpenERPJeff** [comment]
产品的多个供应商这个需求确实普遍存在，但是存在一个管理深度的问题。如果只是记录一下匹配关系，加个多对多就可以了。如果要管到具体供货价格，甚至采购单切换供应商时行项目价格实时更新，产品缺货时列出供应商供货周期和价格支持采购决策，甚至规定各供应商年度配额，以及建议增加订单数量以享受批量折扣。那么扩展性强的做法就不是多对多，而是单独管理供应商供货对照表，这和odoo的设计就很像了

根据gooderp的定位，只做到good即可，那么我们就增加这个表，采购订单产品和供应商修改时读取对应价格即可，其他留给第三方模块或现场顾问去实现吧
