### ISSUE TITLE
资产负债表模板字段的第四列应改为负债和所有者权益（或股东权益）

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#342]
操作系统及版本:
----
重现问题的步骤:
----
会计—配置—资产负债表模板

...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/18207232/15732540/9f5828f6-28b0-11e6-9062-ce760818dbdb.png)

期望的结果:
----
资产负债表模板字段第二个资产改为负债和所有者有权益（或股东权益）

**Comment by yunkuaiji** [comment]
我也发现，已经改了。
