### ISSUE TITLE
允许修改公司logo

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#346]
操作系统及版本: all
----
重现问题的步骤:
----
1. 设置-基础参数
2. 可以修改公司名称，但不能修改公司logo
3.
...

当前结果:
----

截图:

期望的结果:
----
在此界面上增加公司logo，允许用户编辑

**Comment by JasonAxesen** [comment]
已修改

**Comment by OpenERPJeff** [comment]
其实只加一个logo字段就可以了，增加sheet和div并没有提升整个界面的逼格，而是增加了复杂性。as simple as possible
