### ISSUE TITLE
利润表模板字段的金额计算参数改为计算公式

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#353]
操作系统及版本:
----
重现问题的步骤:
----
会计—配置—利润表模板
...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/18207232/15813649/433ad50a-2bf3-11e6-9fd9-8e3d9938fd4c.png)

期望的结果:
----
金额计算参数改为计算公式

**Comment by OpenERPJeff** [comment]
实际上这里改为 科目范围 可能更容易理解

**Comment by floraXiao** [comment]
已修改
