### ISSUE TITLE
对于像“Odoo9.0社区版界面汉化包”这样不用管理库存的商品貌似不能处理。

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#357]
在产品窗体中没有关于虚拟产品的选项。

**Comment by fenshuajiang** [comment]
经咨询，现在可以用其它收入和支出来管理服务的方式来完成。
不过，用销售和采购单来处理服务型产品感觉更符合习惯。

**Comment by OpenERPJeff** [comment]
粉兄，你的手册都是现款交易的，不存在应收、预付、款到货未发、票到货未到、货到票未到这些场景，所以管理的目标是事后记录而非事中控制，所以其他收支作为资金记录附带记一下服务产品销量对你来说应该是不多不少正够用的。引入订单管理增加了操作步骤，必要性不大。

实施过程是按客户应用场景适配不同的功能组合，并非把所有功能都用上就算用好。原则还是那句话：尽力为简，按需就繁

**Comment by OpenERPJeff** [comment]
粉兄，你的手册都是现款交易的，不存在应收、预付、款到货未发、票到货未到、货到票未到这些场景，所以管理的目标是事后记录而非事中控制，所以其他收支作为资金记录附带记一下服务产品销量对你来说应该是不多不少正够用的。引入订单管理增加了操作步骤，必要性不大。

实施过程是按客户应用场景适配不同的功能组合，并非把所有功能都用上就算用好。原则还是那句话：尽力为简，按需就繁

**Comment by OpenERPJeff** [comment]
粉兄，你的手册都是现款交易的，不存在应收、预付、款到货未发、票到货未到、货到票未到这些场景，所以管理的目标是事后记录而非事中控制，所以其他收支作为资金记录附带记一下服务产品销量对你来说应该是不多不少正够用的。引入订单管理增加了操作步骤，必要性不大。

实施过程是按客户应用场景适配不同的功能组合，并非把所有功能都用上就算用好。原则还是那句话：尽力为简，按需就繁

**Comment by OpenERPJeff** [comment]
粉兄，你的手册都是现款交易的，不存在应收、预付、款到货未发、票到货未到、货到票未到这些场景，所以管理的目标是事后记录而非事中控制，所以其他收支作为资金记录附带记一下服务产品销量对你来说应该是不多不少正够用的。引入订单管理增加了操作步骤，必要性不大。

实施过程是按客户应用场景适配不同的功能组合，并非把所有功能都用上就算用好。原则还是那句话：尽力为简，按需就繁

**Comment by OpenERPJeff** [comment]
粉兄，你的手册都是现款交易的，不存在应收、预付、款到货未发、票到货未到、货到票未到这些场景，所以管理的目标是事后记录而非事中控制，所以其他收支作为资金记录附带记一下服务产品销量对你来说应该是不多不少正够用的。引入订单管理增加了操作步骤，必要性不大。

实施过程是按客户应用场景适配不同的功能组合，并非把所有功能都用上就算用好。原则还是那句话：尽力为简，按需就繁

**Comment by OpenERPJeff** [comment]
粉兄，你的手册都是现款交易的，不存在应收、预付、款到货未发、票到货未到、货到票未到这些场景，所以管理的目标是事后记录而非事中控制，所以其他收支作为资金记录附带记一下服务产品销量对你来说应该是不多不少正够用的。引入订单管理增加了操作步骤，必要性不大。

实施过程是按客户应用场景适配不同的功能组合，并非把所有功能都用上就算用好。原则还是那句话：尽力为简，按需就繁

**Comment by fenshuajiang** [comment]
因为后期要对购买者进行售后服务，所以在客户询问时要快速查出此客户曾购买哪些产品，从而提供不同的服务。
        列在资金记录里也行，只要能快速查出客户的购买记录就行。
        后期再测试下，看看能不能满足此需求，最好不要销售订单查一次，然后资金记录里再查一次。

**Comment by fenshuajiang** [comment]
典型场景是，客户A在QQ中进行咨询，我快速在ERP中找到此客户的全部购买记录，基于客户的购买记录进行不同的解答和建议。

**Comment by OpenERPJeff** [comment]
已实现
