### ISSUE TITLE
希望能够在科目明细账里查看到每一条的明细

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#360]
操作系统及版本:
----
重现问题的步骤:
----
会计—账薄—科目明细账.
...

当前结果:
----
不能在科目明细账里查看到明细

截图:
![image](https://cloud.githubusercontent.com/assets/18207232/16003172/f84f3004-318d-11e6-9c1f-2f9133a8a870.png)

期望的结果:
----
![image](https://cloud.githubusercontent.com/assets/18207232/16003151/eb88e572-318d-11e6-9553-f55154cec1cb.png)

**Comment by floraXiao** [comment]
做成结果截图如下：
![Uploading image.png…]()
