### ISSUE TITLE
采购、销售调整单

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#381]
操作系统及版本:
----
重现问题的步骤:

采购订单和销售订单已有收发货记录便不可反审核修改。
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----
新增销售调整单和采购调整单，头上选择对应的订单，确认后将行与原订单合并。

**Comment by OpenERPJeff** [comment]
业务规则： 

- 只可以针对收发货未完成的订单做调整

- 调整数量可以输入负数

- 调整后的订单行数量要大于等于已收货或发货的数量

如果不符合这些规则，审核时报错。

**Comment by floraXiao** [comment]
已完成
