### ISSUE TITLE
新增产品错误

### ISSUE THREAD

**Issue by jaronemo** [osbzr/gooderp_addons#388]
操作系统及版本:
----
重现问题的步骤:
----
1. 新增商品 如图 ：
![image](https://cloud.githubusercontent.com/assets/8476734/16236803/385fde1c-380c-11e6-8e69-6197b9cac0c6.png)

2.立即报错，如图：
![image](https://cloud.githubusercontent.com/assets/8476734/16236822/4b00943a-380c-11e6-9090-e5497eeb8342.png)

3.
...

当前结果:
----

截图:

期望的结果: 为何不能只是单纯的新增产品项目了？
----

**Comment by OpenERPJeff** [comment]
代码已更新，旧数据库需要更新core模块

**Comment by jaronemo** [comment]
OK..测试下！
