### ISSUE TITLE
销售或采购订单中 “含税单价”一栏名称需要修改

### ISSUE THREAD

**Issue by fanliugen** [osbzr/gooderp_addons#392]
操作系统及版本:
----
重现问题的步骤:
----
当采购或销售时，不含税时，也就是税率一栏改为0时，这边如果还是显示含税单价，会产生歧义。希望把这里修改一下

当前结果:
----

截图:

期望的结果:
----

**Comment by OpenERPJeff** [comment]
如果该公司关注进项税，那么即使本行是0税率，含税价和单价相等逻辑上并没有问题。

若果该公司不关注进项税，那么可以用权限把行上涉税字段（包括含税价）隐藏，所以也不是问题。
