### ISSUE TITLE
类别里的科目应整成必填项，如为空，在付款时会提示错误。

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#399]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----

**Comment by lilnn** [comment]
配置-客户-客户类别里的科目也应为必输项

**Comment by floraXiao** [comment]
已修改，https://github.com/osbzr/gooderp_addons/pull/446/commits/c3e3b98b23919071d1d0f04c2e2e19ff623cdf16

**Comment by floraXiao** [comment]
已修改，https://github.com/osbzr/gooderp_addons/pull/446/commits/c3e3b98b23919071d1d0f04c2e2e19ff623cdf16
