### ISSUE TITLE
发货单里选择批号后，字段里的内容显示了很多内容，而且无批号。

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#407]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----

**Comment by floraXiao** [comment]
![image](https://cloud.githubusercontent.com/assets/13793204/16681801/6e71c0ea-4529-11e6-8ea7-0ddc5fe8301a.png)
