### ISSUE TITLE
增加凭证模板功能

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#410]
操作系统及版本:
----
重现问题的步骤:

有些相同的凭证每个月都要录入几笔

当前结果:
----
只能手工重复输入

截图:

期望的结果:
----
有一个凭证模板，可以选择并带出凭证行客户和摘要，功能类似组装单的模板

**Comment by yunkuaiji** [comment]
好啊

**Comment by lilnn** [comment]
测试通过
