### ISSUE TITLE
调拨单里的产品属性不能选择，销售发货单产品的属性不是必输

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#416]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
![image](https://cloud.githubusercontent.com/assets/18207232/16643512/bd0b0f46-4447-11e6-8eb2-78e851ce17cd.png)

截图:

期望的结果:
----
调拨单里的产品属性可以选择且为必输，销售发货单产品属性为必输

**Comment by floraXiao** [comment]
这两个单子里的明细行上产品属性是这样设计的：选择了产品后，当产品有属性时则明细行上属性为必输，无时为只读。考虑不是bug

**Comment by floraXiao** [comment]
已修改
