### ISSUE TITLE
系统自动生成的入库单中的辅助单位数量和采购单不符

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#423]
![4](https://cloud.githubusercontent.com/assets/7471985/16711584/cc2841b0-4695-11e6-807f-c143a69f5491.png)
![11](https://cloud.githubusercontent.com/assets/7471985/16711591/f8ffe2f6-4695-11e6-8d76-c0df44b44494.png)
![22](https://cloud.githubusercontent.com/assets/7471985/16711598/29ec57e6-4696-11e6-93a7-6dee16ae379e.png)
辅助单位数量应该为5或0（看如何设计此处主单位数量和辅助单位数量之间的关系），为1肯定不正确。

**Comment by floraXiao** [comment]
已修改
