### ISSUE TITLE
供应商，客户，在付款的时候三大必须要有，营业执照号，税务登记号，法人，银行账户等

### ISSUE THREAD

**Issue by 200864558** [osbzr/gooderp_addons#440]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----

**Comment by OpenERPJeff** [comment]
partner表增加三个字段，非必输
======
客户
----
税务登记号

供应商
----
开户行

银行账号

**Comment by floraXiao** [comment]
已完成
