### ISSUE TITLE
采购收货、销售出库也该显示在仓库菜单下

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#449]
操作系统及版本:
----
重现问题的步骤:
----
1. 仓库收货或发货
2. 在仓库菜单下看不到采购收货单和销售发货单
3.
...

当前结果:
----
在仓库菜单下看不到采购收货单和销售发货单

截图:

期望的结果:
----
在仓库菜单下也有采购收货单和销售发货单

并且这两个单据的列表视图不应该有新建按钮

**Comment by fenshuajiang** [comment]
同意。
