### ISSUE TITLE
请购

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#450]
操作系统及版本: all
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
采购部门直接根据线下需求新建采购订单。

截图:

期望的结果:
----
商品需求部门提交请购单，审批后经采购合并生成采购订单草稿。

**Comment by jeffery9** [comment]
询价/采购的条件只要 采购没有 确认， 就能被 合并。。。 合并的条件   同供应商、同时间、同交货地点
