### ISSUE TITLE
需要外币

### ISSUE THREAD

**Issue by xuanyimin** [osbzr/gooderp_addons#456]
无外币，希望增加外币。
1.销售订单
2.销售发票
3.会计科目（增加外币与是否结转汇兑损益）
4.资金转帐单
[Pending]5.月末结转汇兑损益

**Comment by xuanyimin** [comment]
采购订单和采购发票也有可能会出现外币！

**Comment by xuanyimin** [comment]
1.增加汇率设置：期间，币别，汇率（4位小数）
2.科目上设置币种，是否月末调汇
3.资金从对应科目上取得币种
4.销售增加单头上币别（币别从客户对应科目上取得，不可以更改）和行中外币金额。
5.资金同样从客户和帐户的科目上取币别（现不支持非一致的情况）（资金转帐单除外，非资金转帐单外，汇率只能看不能改）。
6.月末调汇时，外币金额＊汇率－现在本位币金额（cny）为汇兑损益，生成凭证。

**Comment by OpenERPJeff** [comment]
需要测试

**Comment by lilnn** [comment]
已测试：1、在销售订单里不输入税，计算出的人民币价格是不含税的；
               2、汇兑损益不能生成。

**Comment by xuanyimin** [comment]
最后一步写不清楚了，过几天脑子清楚了再写〜有人高兴帮忙写吗？

**Comment by l315276651** [comment]
在你的pr名字前面加 **[Pending]** 代表这个pr **待做**
