### ISSUE TITLE
关于初始化！

### ISSUE THREAD

**Issue by xuanyimin** [osbzr/gooderp_addons#457]
现在管理员录入期初值即生成凭证无会计依据，希望改成有一个单据菜单。
上面可以选择科目，录入期初值，计算（跟据客户或供应商上设置的会计科目sum值填入）借贷一致后可以生成期初会计凭证，一但期初会计凭证生成完成（指凭证生成且确认记帐），则在客户和供应商上无法再录入期初值。

**Comment by OpenERPJeff** [comment]
由于我们把 现金银行报表、客户对账单、供应商对账单 都放在了资金模块，如果直接在凭证里录入期初这些报表是取不到数据的
