### ISSUE TITLE
无有关增值税的内容

### ISSUE THREAD

**Issue by xuanyimin** [osbzr/gooderp_addons#459]
操作系统及版本:
----
重现问题的步骤:
----无有关增值税的内容
1. 采购进项增值税
2.销售销项增值税
3.partner和商品上税率设置
...

当前结果:
----
1.采购时有税率，在发票时无生成凭证！

截图:

期望的结果:
----

**Comment by floraXiao** [comment]
https://github.com/osbzr/gooderp_addons/pull/465/commits/c6b45b1897f163d31c48faba269db7dfdb61f9eb
