### ISSUE TITLE
联系人上直接省市县镇和街道门牌号

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#464]
操作系统及版本: 安装了 province_city_county
----
重现问题的步骤:
----
1. 客户菜单

2. 新建客户

3.新建客户的联系人
...

当前结果:
----
地址需要下拉，新建一条相关记录，实际上这个相关记录大部分时候只用于此联系人

截图:

期望的结果:
----
联系人上直接选择省市县，输入镇，输入街道门牌号，去掉冗余的表

**Comment by floraXiao** [comment]
https://github.com/osbzr/gooderp_addons/pull/465
