### ISSUE TITLE
采购模块里由含税价格和税率计算不含税价格

### ISSUE THREAD

**Issue by fanliugen** [osbzr/gooderp_addons#466]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
只能填不含税价格

截图:

期望的结果:
----
可以自主根据情况填含税价和不含税价

**Comment by OpenERPJeff** [comment]
单价和含税价肯定是一个要输入一个要计算的，不可能两个都可输入

首先互相算会死循环，其次不给算全手输太不人性化

现在的设计是根据单价和税率算含税价，issue的要求是否可以理解为根据含税价和税率计算（不含税）单价？

**Comment by floraXiao** [comment]
已修改
