### ISSUE TITLE
新数据库安装完gooderp所有模块后，库存余额表和批号状态表菜单报错

### ISSUE THREAD

**Issue by youring** [osbzr/gooderp_addons#48]
未创建任何记录的情况下，点击**仓库--报表--库存余额表和批号状态表**，都会报错：
![20160402154942](https://cloud.githubusercontent.com/assets/4132418/14225129/97d30f10-f8ea-11e5-8216-ddb7fbb24d3f.jpg)

> Uncaught TypeError: viewclass is not a constructor
http://10.0.0.103:8069/web/js/web.assets_backend/00919f9:3143

**Comment by youring** [comment]
原因：安装时addon文件夹未加入web_graph模块。
注：此模块具有自动安装属性 'auto_install': True，故不易发现。
建议warehouse模块添加依赖：web_graph。

**Comment by youring** [comment]
目前为止GoodERP依赖的官方模块除了base还有：
base_setup
decimal_precision
mail
web
web_graph
web_kanban

**Comment by OpenERPJeff** [comment]
会在发布绿色版时包含这些模块
