### ISSUE TITLE
制单人的审核权限

### ISSUE THREAD

**Issue by zqwang777801** [osbzr/gooderp_addons#501]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
既是制单人，又可以做制单审核人

截图:

期望的结果:
----
最好制单人和单子审核权限分开

**Comment by OpenERPJeff** [comment]
如果一个流程只需要一个人完成，没有第二个用户怎么办？

项目上可以根据客户需要增加权限做这个限制，产品本身加上新的权限组要去掉就难了

**Comment by zqwang777801** [comment]
比如在采购功能里，把采购订单审核权限单独开来，根据角色是否赋予他这个权限。其实如果就一个用户来完成，是不是就没必要审核了。权限控制有待jeff大神的改进。

**Comment by OpenERPJeff** [comment]
GoodERP中的 待审核 和 已审核 的状态逻辑是这样：

待审核的单据还没有输入完成，或未达到执行条件。审核的动作是确认单据开始执行，同时生成后续单据。所以同其他软件的审批过程并不一样，更类似复核 （double check）。项目上如果有需要可以新增组对按钮增加权限，产品本身还是以流程简单记录业务事实为基准。

我暂时关闭这个issue，有异议的话我们可以继续探讨。
