### ISSUE TITLE
制单人制作的采购入库单，供应商联想，商品鼠标时。其他人在审核的时候会出现下列字段无效，入库明细的的bug，无法审核通过，制单人自己审核没问题。

### ISSUE THREAD

**Issue by zqwang777801** [osbzr/gooderp_addons#502]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/20652329/17204711/9e934f90-54d9-11e6-8357-13750588378e.png)

期望的结果:
----

**Comment by floraXiao** [comment]
不能重现，是否是鼠标有批次而入库单明细行上鼠标的批次没输入？

**Comment by OpenERPJeff** [comment]
无法重现，请帮忙截全图，应该是某些必输字段没有填充
