### ISSUE TITLE
序号重排希望可以单独出来！

### ISSUE THREAD

**Issue by xuanyimin** [osbzr/gooderp_addons#513]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
1.当做凭证多的时候，可能前面就有断号，希望可以早点将断号补平！
2.补断号后能否给个反馈：自己变过号的凭证我们需要去重写编号！

截图:

期望的结果:
----

**Comment by OpenERPJeff** [comment]
分出来应该可行，但需要工作量。

早点儿补平逻辑上比较复杂，希望能接收现状

既然重排了那所有号都可能变了，你说的重写编号是在手工凭证上写字是么？这个工作习惯可能要改掉了。

**Comment by xuanyimin** [comment]
原来做的时候不是有个编号吗？重排后不是编号可能变了？我想知道哪些编号给改变了，好让我把纸质上的对应改掉，在装订凭证时比较清楚。

**Comment by OpenERPJeff** [comment]
那你干脆装订凭证的时候再写编号吧。如果前面断号，肯定后面所有的都被修改了，这样改掉很麻烦的。
