### ISSUE TITLE
当采购商品中即有国内原材料也有国外原材料时！

### ISSUE THREAD

**Issue by xuanyimin** [osbzr/gooderp_addons#514]
操作系统及版本:
----
重现问题的步骤:
----
1. 生成凭证我们希望分到二个不同科目，但现在系统只会生成一个科目，不能按采购物的不同分别入不同会计科目。
2.
3.
...

当前结果:
----
借：原材料－国内
        贷：应付帐款

截图:

期望的结果:
----
借：原材料－国内
        原材料－国外
        贷：应付帐款

**Comment by OpenERPJeff** [comment]
暂无法实现

**Comment by xuanyimin** [comment]
产品分类上面的科目好象没用起来呀〜为什么不在产品上取科目呢？

**Comment by OpenERPJeff** [comment]
https://github.com/osbzr/gooderp_addons/issues/532  实现了这个就可以了
