### ISSUE TITLE
资金无法初始化

### ISSUE THREAD

**Issue by xuanyimin** [osbzr/gooderp_addons#515]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----
希望跟应收应付一样有个初始金额进去的地方

**Comment by OpenERPJeff** [comment]
参照业务伙伴余额

新增一个字段 init_balance，写一个写入方法触发根据这个值生成一个其它收入单，类型为 期初（可以新建一个叫做期初的类别，指向9999科目）

**Comment by Judystudy** [comment]
我来做

**Comment by lilnn** [comment]
已测试通过。
