### ISSUE TITLE
GoodERP采购模块-报表采购汇总表（按商品）、（按供应商）查询时报错

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#517]
操作系统及版本:
----
重现问题的步骤:
----
1. 采购
2.报表
3.采购汇总表（按商品）、采购汇总表（按供应商）
...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/18207232/17917048/4c5271bc-69eb-11e6-899d-a1a85ba2f2f6.png)

期望的结果:
----

**Comment by yunkuaiji** [comment]
初零除？

**Comment by OpenERPJeff** [comment]
由于入库和退货的数量一致，导致入库数量合计为0，用金额去除以数量算价格的时候就出现了除零错误。已修正。
