### ISSUE TITLE
GoodERP销售模块-报表销售汇总表（按商品）、（按供应商）（按销售人员）查询时和采购报表报的错误一样

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#518]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----

**Comment by OpenERPJeff** [comment]
由于销售出库和退货的数量完全一致，合计销售出库数量为0，用销售额去除数量得到的单价就导致了除零错误。已修复
