### ISSUE TITLE
其他付款单税额不可以修改

### ISSUE THREAD

**Issue by xuanyimin** [osbzr/gooderp_addons#521]
操作系统及版本:
----
重现问题的步骤:
----
1. 税额是乘出来不可以修改，故有可能会与实际给的发票不符。
2.
3.
...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/19392611/18075245/a58b9d58-6ea5-11e6-9f14-afbdd7fbc209.png)

期望的结果:
----
请去掉188行readonly=True,

**Comment by Judystudy** [comment]
您说的是要修改 tax_amount 字段？
计算类型是不能修改的。

**Comment by xuanyimin** [comment]
是的，会有1分钱的差异

**Comment by OpenERPJeff** [comment]
已修改，需要测试一下

**Comment by Judystudy** [comment]
[FIX]core depends module mail;change calculation method of tax amount in other money order line #536

**Comment by lilnn** [comment]
已测试通过
