### ISSUE TITLE
发货单生成的源单和付款都取发货单日期

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#529]
操作系统及版本:
----
重现问题的步骤:
----
1. 新建发货单，日期2015-01-01的
2.在2016年9月1日审核发货单
3.
...

当前结果:
----
生成的源单和付款单都是2016-9-1的

截图:

期望的结果:
----
因为客户可能补录数据，希望这里源单和付款单日期可以和发货单保持一致

**Comment by OpenERPJeff** [comment]
https://github.com/osbzr/gooderp_addons/pull/528/commits/021a317a6c47986f07a49e72db9e9009db173d0b

之前改过，造成测试大面积失败。只需按此版本修改并修复ci（创建对应的会计期间）即可

**Comment by lilnn** [comment]
测试通过
