### ISSUE TITLE
采购入库单审核时生成凭证

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#532]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----
采购入库单确认后，生成会计凭证

借： 商品分类对应的会计科目  一般是库存商品
贷：类型为支出的类别对应的会计科目  一般是材料采购

当一张入库单有多个产品的时候，按对应科目汇总生成多个借方凭证行。

**Comment by OpenERPJeff** [comment]
其它入库单也需要

**Comment by Judystudy** [comment]
我来做。

**Comment by OpenERPJeff** [comment]
这个功能很重要，请测试一下。

**Comment by lilnn** [comment]
已测试通过。
