### ISSUE TITLE
会计账簿向导输入参数给默认值

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#533]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
每次弹窗出来的四个字段都是必输且无默认值，在查看当前结果的常用场景下稍嫌麻烦

截图:

期望的结果:
----
如报表参数为 会计期间，默认值为 当前日期所属的会计期间

如报表参数为起止期间，默认值为从 当前日期所在年的1月1日所属会计期间 到 当前日期所属的会计期间

科目默认为从code最小的科目到code最大的科目

**Comment by gilbert-yuan** [comment]
已经加过了,请测试下.
