### ISSUE TITLE
有其他模块生成的会计凭证直接审核

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#534]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
生成的是草稿凭证，需要一个个点审核。没有（也不该有）批量审核的功能

截图:

期望的结果:
----
生成凭证后直接审核

**Comment by lilnn** [comment]
测试通过

**Comment by lilnn** [comment]
由其他入库单生成的会计凭证为草稿状态，采购入库生成的借库存商品贷材料采购的凭证为草稿状态。

**Comment by OpenERPJeff** [comment]
囡姐测试一下

**Comment by lilnn** [comment]
测试通过
