### ISSUE TITLE
建议：在组装单和拆卸单里选择模板后，在组合件的数量增加或减少时，子件的数量会相应的增加或减少

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#538]
操作系统及版本:
----
重现问题的步骤:
----
1. 仓库
2.组装单或者拆卸单
3.选择模板
...

当前结果:
----

截图:

期望的结果:
----
![image](https://cloud.githubusercontent.com/assets/18207232/18163420/85847f4c-706d-11e6-9312-8e9e038a7f82.png)

**Comment by floraXiao** [comment]
组合件和子件都为wh_move_line，没法做onchange，也不好做成计算型字段，所以此需求无法实现

**Comment by OpenERPJeff** [comment]
可以把组合件的产品和数量字段放在组装单或拆卸单上，并onchange保证其与组合件行的数据同步。

新建组 “组装拆卸支持多对多组合”，把组合件这个one2many设置为只有这个组可以看。
