### ISSUE TITLE
给每个字段增加 help 属性

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#549]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----
用户数据时鼠标悬停在字段上可以看到这个字段的涵义和系统行为对这个字段的影响

**Comment by floraXiao** [comment]
做采购和销售模块的help

**Comment by Judystudy** [comment]
做资金和仓库的help

**Comment by gilbert-yuan** [comment]
homepage and finance

**Comment by lilnn** [comment]
已测试
