### ISSUE TITLE
利润表计算有误

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#553]
操作系统及版本:
----
重现问题的步骤:
----
1. 只有费用34000
2.
3.
...

当前结果:
----
利润为 34000

截图:
![image](https://cloud.githubusercontent.com/assets/1857069/18239007/caff2eaa-7374-11e6-8d56-6fa9e5e76cea.png)

期望的结果:
----
利润为 -34000

**Comment by yunkuaiji** [comment]
if subject_vals_in and subject_vals_out:
                    total_sum = sum(subject_vals_out)-sum(subject_vals_in)
                else:
                    if subject_vals_in:
                        total_sum = sum(subject_vals_in)
                    else:
                        total_sum = sum(subject_vals_out)

**Comment by OpenERPJeff** [comment]
![image](https://cloud.githubusercontent.com/assets/1857069/18240385/fae1a2b6-737d-11e6-91ab-8343cd2369fe.png)

还是不对

最上面的数字不应该是负数

**Comment by yunkuaiji** [comment]
好的

**Comment by yunkuaiji** [comment]
![filehelper_1473075534727_51](https://cloud.githubusercontent.com/assets/5527229/18246796/91f01f94-73a0-11e6-9172-49933aa1c501.png)

**Comment by yunkuaiji** [comment]
搞定

**Comment by lilnn** [comment]
已解决
