### ISSUE TITLE
固定资产：应分为小规模和一般纳税人

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#555]
操作系统及版本:
----
重现问题的步骤:
----
1. 固定资产
2.
3.
...

当前结果:
----

金额减掉净残值除以折旧期间数
截图:

期望的结果:
----
如果企业为小规模纳税人，不可以抵扣，那么每月折旧额为价税合计减掉净残值除以折旧期间数；如果企业为一般纳税人，可以抵扣，每月折扣额为金额减掉净残值除以折旧期间数。

**Comment by OpenERPJeff** [comment]
小规模纳税人可以不输入税 那个字段就好了
