### ISSUE TITLE
会计-默认设置里勾选是否重置凭证号的问题

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#557]
操作系统及版本:
----
重现问题的步骤:
----
1. 会计
2.默认设置
3.
...

当前结果:勾选重置凭证号、凭证号重置间隔为每月后，不能月末结账系统会报错；不勾选可以结账，但是生成的结转凭证号不连续。
----

截图:
![image](https://cloud.githubusercontent.com/assets/18207232/18260916/f94c1eb6-7424-11e6-8902-bbee727e31eb.png)
![image](https://cloud.githubusercontent.com/assets/18207232/18260975/7b135f04-7425-11e6-8748-0ccd4b419a80.png)
![image](https://cloud.githubusercontent.com/assets/18207232/18261060/30a1b30c-7426-11e6-8a86-1e440d84f5cb.png)
![image](https://cloud.githubusercontent.com/assets/18207232/18261182/755ff7c8-7427-11e6-9f4d-d1548939f0e3.png)

期望的结果:
----
勾选此项可以月末结账，结账后重置会计凭证。不勾选此项，可以月末结账，生成的凭证号连续。

**Comment by yunkuaiji** [comment]
重载write 有问题，可能修改。

**Comment by yunkuaiji** [comment]
已OK

**Comment by OpenERPJeff** [comment]
我记得遇到的报错是 取不到上一个期间的最后一张凭证号，测试数据库只有一个期间，勾选了重排凭证号再结账就会报错。

@yunkuaiji 感觉只是调整代码顺序无法解决此问题

@lilnn 报issue请重现问题复制报错信息并截图，以免误解

**Comment by yunkuaiji** [comment]
测试数据库只有一个期间，就不应该取：上一个期间的最后一张凭证号 才对啊。程序有判断是否有上一期间的。

进一步优化了代码，也进行了各种可能的测试，代码已提交，请大家再测试。

**Comment by lilnn** [comment]
已经解决
