### ISSUE TITLE
固定资产变更记录显示业务伙伴

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#563]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----

**Comment by xuanyimin** [comment]
![24f556a3-3b84-40b2-aa78-3ef5ab7e35be](https://cloud.githubusercontent.com/assets/19392611/18266676/6a2b76d0-744e-11e6-9dab-39cff30812bf.png)

**Comment by OpenERPJeff** [comment]
请测试一下

**Comment by lilnn** [comment]
只变更业务伙伴不生成变更明细

**Comment by OpenERPJeff** [comment]
大小鱼讲过，固定资产变更的场景是 大修理 导致的固定资产价值变动，这里的往来单位是执行大修理的供应商，并非原资产购置单位。所以只改这个没啥意义的。

**Comment by lilnn** [comment]
已解决
