### ISSUE TITLE
列表上如果数值为零,则显示为空.

### ISSUE THREAD

**Issue by gilbert-yuan** [osbzr/gooderp_addons#573]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
列表上数值为零 就显示 0.000

截图:

期望的结果:
----
希望数值为零 显示 为 空白

**Comment by gilbert-yuan** [comment]
这个自己来做

**Comment by leangjia** [comment]
围观大神自问自解！厉害了！

**Comment by OpenERPJeff** [comment]
已测试通过
