### ISSUE TITLE
收付款单、转账单增加 折扣科目字段，用于记录付款和核销的差异

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#574]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----
如果整单折扣不为0，审核时检查这个字段必须输入。

**Comment by Judystudy** [comment]
我来做

**Comment by OpenERPJeff** [comment]
已合并，测试一下

**Comment by lilnn** [comment]
收款单和付款单测试通过。
