### ISSUE TITLE
odoo8.0上安装gooderp报错问题

### ISSUE THREAD

**Issue by luoguizhou** [osbzr/gooderp_addons#576]
操作系统及版本:
windows 10

![image](https://cloud.githubusercontent.com/assets/5688576/18372560/3219abda-7670-11e6-890b-556f07144abd.png)

重现问题的步骤:
----
1.  下载官网的odoo8.0源码，具体版本看图
2.   good erp进行安装 
3.
...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/5688576/18372553/28b0ada0-7670-11e6-8650-00f8296c4ded.png)

期望的结果:
----

**Comment by luoguizhou** [comment]
odoo 8.0版本
![image](https://cloud.githubusercontent.com/assets/5688576/18372523/e818ee74-766f-11e6-84ac-52438ca137d2.png)

**Comment by luoguizhou** [comment]
错误信息
![image](https://cloud.githubusercontent.com/assets/5688576/18372545/1c959864-7670-11e6-82e9-6bc91fd83242.png)

**Comment by OpenERPJeff** [comment]
用户确认最新版gooderp已解决
