### ISSUE TITLE
新建固定资产已审核已折旧，可以删除；新建资产没有折旧，删除资产，生成的会计凭证不会删除。

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#579]
操作系统及版本:
----
重现问题的步骤:
----
1. 会计
2.固定资产
3.
...

当前结果:
----
新建固定资产已审核已折旧，可以删除

截图:

期望的结果:
----
已折旧不能删除

**Comment by xuanyimin** [comment]
已更正。重起了反审核。

**Comment by lilnn** [comment]
大鱼小鱼，代码提交了吗？

**Comment by lilnn** [comment]
固定资产审核状态不能删除，已测试通过。
