### ISSUE TITLE
在采购入库单的采购费用行输入金额，审核后的入库单反审核，采购费用行生成的会计凭证没有删除。销售也是同样的情况。

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#582]
操作系统及版本:
----
重现问题的步骤:
----
1. 采购订单
2.采购入库单-采购费用行
3.
...

当前结果:
----

截图:

期望的结果:
----

**Comment by floraXiao** [comment]
https://github.com/osbzr/gooderp_addons/pull/583/commits/96c800fa73a5577c9a76b07b0eb7035de0290ce0

**Comment by lilnn** [comment]
测试通过
