### ISSUE TITLE
月末结账前生成发出成本结转凭证

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#584]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
发货单不生成凭证，仓库收发存汇总表显示先进先出成本

截图:

期望的结果:
----
增加新菜单 会计-月末结转-发出成本

弹出向导，要求输入期间，确定

取出所有本月的销售发货、其它出库和组装拆卸记录，根据产品分类汇总，计算
本月该产品的结存单价 = （上月该产品的成本余额 + 本月入库成本 ）/ (上月数量余额 + 本月入库数量)

则本月发出成本 = 结存单价 * 发出数量

生成会计凭证，借：主营业务成本 结存单价 * 发出数量 填充商品
                          贷：库存商品  结存单价 * 发出数量 填充商品
多个产品生成的会计凭证合并为一张凭证

**Comment by lilnn** [comment]
测试通过
