### ISSUE TITLE
软件功能使用频率统计

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#585]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
我们不知道谁在用gooderp，也不知道哪些功能最常用

截图:

期望的结果:
----
1、用户修改公司名称的时候，调用一个网址，发送这个公司名称到我这里
2、用户进入每个action，调用一个网址，发送这个action的名称到我这里

这样我知道谁在用，在用哪些功能

当然这个可以做成一个自动安装的模块，并在创建数据库的页面说明，提示用户可以通过卸载这个模块的方式停掉信息发送

模块名叫 gooderp_statistics

**Comment by OpenERPJeff** [comment]
url也开是 www.gooderp.org/statistics/company 和 www.gooderp.org/statistics/action

**Comment by leangjia** [comment]
姐夫早！
谢谢你们的辛勤劳动，gooderp目前个人试用中。
请知悉！

**Comment by OpenERPJeff** [comment]
已实现
