### ISSUE TITLE
组装单拆卸单报错

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#586]
操作系统及版本:
----
重现问题的步骤:
----
1. 在有demo数据的系统
2.进入组装单或拆卸单列表
3.进入会计凭证菜单也报相同的错误
...

当前结果:
----
  File "C:\00_osbzr\gooderp\gooderp\openobject\openerp\sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: SELECT id FROM "wh_move_line" WHERE id IN (false, false)
                                               ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

截图:

期望的结果:
----

**Comment by lilnn** [comment]
仓库-模板也会报同样的错误。

**Comment by lilnn** [comment]
已不在报错。
