### ISSUE TITLE
 客户信用额度管控

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#587]
操作系统及版本:
----
重现问题的步骤:
----
1. 客户有余额10000
2. 客户下采购单
3. 发货
...

当前结果:
----
无提示

截图:

期望的结果:
----
在客户字段上增加信用额度字段，如果本次 发货金额+客户应收余额 大于客户信用额度，报错。

**Comment by Judystudy** [comment]
我来做

**Comment by lilnn** [comment]
已测试通过
