### ISSUE TITLE
各模块单据打印docx模板定义

### ISSUE THREAD

**Issue by OpenERPJeff** [osbzr/gooderp_addons#596]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----

截图:

期望的结果:
----

**Comment by OpenERPJeff** [comment]
会计凭证
销售发货单
销售退货单
采购入库单
采购退货单
调拨单
盘点单
其它入库单
其他出库单 已实现
组装单
拆卸单
收款单
付款单
结算单
核销单
其他收入单
其他支出单
资金转账单
购货订单
采购调整单
销货订单
销售调整单

在模块的template目录下新增docx文件，并在模块的xml文件中声明，测试通过后即可提交

**Comment by gilbert-yuan** [comment]
先做销货 采购

**Comment by floraXiao** [comment]
调拨单

**Comment by floraXiao** [comment]
https://github.com/osbzr/gooderp_addons/pull/608

**Comment by floraXiao** [comment]
组装单、拆卸单

**Comment by lilnn** [comment]
除了结算单不能打印都可以打印。
