### ISSUE TITLE
docx模板支持图片字段

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#599]
## 重现问题的步骤:
1. 修改其它出库单docx模板，试图输出公司logo

2.使用 {{obj.create_uid.company_id.logo}}

3.
...
## 当前结果:

打印出来的docx文件对应位置像是的是图片的二级制字符

截图:
## 期望的结果:

显示图片

**Comment by luoguizhou** [comment]
你好，jeff。你不是说这个问题要修改底层吗？我之前咨询过你的，动态图片在报表中的处理？
还有如果能实现，是否可以实现图片的缩放？

**Comment by GoodERPJeff** [comment]
https://zb.oschina.net/project/12cac7a6f8f2fe7f

在oschina上众包解决了此问题
