### ISSUE TITLE
关于代码中使用中文字符的规范问题

### ISSUE THREAD

**Issue by buke** [osbzr/gooderp_addons#60]
9.0 的代码中可翻译字符，已将非中文字符过滤掉。即如果在py xml 中使用中文字符，将无法翻译为其它语言。

参考代码：https://github.com/odoo/odoo/blob/9.0/openerp/tools/translate.py#L814  def push_translation

如考虑以后升级至9.0（也不排除官方升级8.0 的核心代码），请在代码中使用英文及数字字符。

**Comment by OpenERPJeff** [comment]
专业术语，中文表达都词穷，要求英文难以实现啊。

暂不考虑9.0，如果必要可以把这块代码做个patch

谢谢大神指导

**Comment by buke** [comment]
谢谢
