### ISSUE TITLE
仓库-呆滞料报表

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#601]
操作系统及版本:
----
重现问题的步骤:
----
1. 客户需要知道哪些产品入库很久但仍没有销售掉
2.
3.
...

当前结果:
----
可以在仓库-报表-库存调拨里筛选 剩余数量大于0的入库记录，但未显示入库日期

截图:

期望的结果:
----
新增报表

仓库-报表-呆滞料

点击弹出向导 

可输入仓库 （可不输入）
必输 第一阶段天数 第二阶段天数 第三阶段天数

筛选目标仓库是所选仓库的剩余数量大于零的入库记录，根据（当前日期-入库日期相差的天数）将产品数量分到报表的4个字段，x天内的，xx天内的，xxx天内的，大于xxx天的数量，一个产品只输出一行。

**Comment by lilnn** [comment]
已测试
