### ISSUE TITLE
仓库单据新建时不能直接扫描条码

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#623]
操作系统及版本:
----
重现问题的步骤:
----
1. 为白色键盘定条码 white

2. 新建其它入库单

3.在条码中输入white回车

...

当前结果:
----
界面返回到列表视图，记录未保存

现在要求的操作顺序是，新建单据，然后保存，然后再扫码增加行

截图:

期望的结果:
----
新建或编辑时扫码，系统先自动保存当前记录，然后接收扫码添加行

@gilbert-yuan

**Comment by ie-it** [comment]
之前是可以的。
