### ISSUE TITLE
同一个业务伙伴不能有两张未审核的收付款

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#626]
操作系统及版本:
----
重现问题的步骤:
----
1. 审核发货单，生成计算单
2. 新建付款，输入业务伙伴，看到带出了结算单
3. 新建另一张付款，输入业务伙伴
...

当前结果:
----
那张结算单又带出来了

截图:

期望的结果:
----
报错：
该客户有未审核的收款单

或

该供应商有未审核的付款单

**Comment by lilnn** [comment]
测试通过。
