### ISSUE TITLE
期初凭证行生成到同一张凭证上

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#627]
操作系统及版本:
----
重现问题的步骤:
----
1. 
2.
3.
...

当前结果:
----
每个科目的期初都生成了独立的会计凭证，期初期间凭证比较多。

截图:

期望的结果:
----
通过客户期初、供应商期初、账户期初、固定资产期初生成的会计凭证，合并到一个

**Comment by xuanyimin** [comment]
没人做？那我来做吧〜

**Comment by xuanyimin** [comment]
通过客户期初、供应商期初、账户期初、固定资产期初生成的会计凭证，合并到一个，这些都已完成，测试，测试，
期中固定资产期初是在期初凭证上取得期初。
todo 仓库期初

**Comment by xuanyimin** [comment]
仓库推式初始化已完成，测试，测试，测试重要的事要说三次

**Comment by lilnn** [comment]
通过客户期初、供应商期初、账户期初、固定资产期初生成的会计凭证，合并到一个，已测试，输入期初金额，在启用账套的日期生成一条凭证，再次输入金额，会生成另外一张凭证，不会合并在一起。
![image](https://cloud.githubusercontent.com/assets/18207232/18859348/cabee10a-84a5-11e6-8548-e698f5787f87.png)

**Comment by lilnn** [comment]
凭证上没有期初余额科目，借贷不平。另外‘引入固定资产’是怎么用的？
![image](https://cloud.githubusercontent.com/assets/18207232/18900042/6c092b22-8570-11e6-9d0a-1f493c050ab5.png)

**Comment by lilnn** [comment]
测试通过
