### ISSUE TITLE
主数据-商品-条形码需要添加重复限制

### ISSUE THREAD

**Issue by ie-it** [osbzr/gooderp_addons#629]
## 操作系统及版本:
试用：  [http://gooderp.osbzr.net/login?db=gooderp&login=admin&key=good](http://gooderp.osbzr.net/login?db=gooderp&login=admin&key=good)
## 重现问题的步骤:
----

1.  修改一个商品条形码为414，保存成功
2. -再修改一个商品条形码为414，保存成功

我看了下代码，应该是没对上号：
`barcode = fields.Char(u'条形码')`

`_sql_constraints = [
          ('ean_uniq', 'unique (ean)', u'该条码已存在'),
     ]`

## 当前结果:
----
商品条形码就重复了，入库扫描时提示
`Expected singleton: goods(2, 3,)`

## 期望的结果:
商品条形码唯一限制，不允许保存相同的条形码。

**Comment by lilnn** [comment]
已测试通过
