### ISSUE TITLE
订单明细表不必要字段隐藏

### ISSUE THREAD

**Issue by JasonAxesen** [osbzr/gooderp_addons#655]
## 问题:

订单明细表的销售额 并没有考虑所有的折扣以及成本分摊之类，所以订单明细表上的类似金额这些字段其实是没有意义的，放在上面反而会误导客户。
...
## 当前结果:

截图:

**Comment by JasonAxesen** [comment]
![image](https://cloud.githubusercontent.com/assets/18279414/18939130/c8821b5a-8630-11e6-9a91-97dd963bee71.png)

明细表是查看数量的话，这些价格的字段都可以不要的吧？

**Comment by JasonAxesen** [comment]
![image](https://cloud.githubusercontent.com/assets/18279414/18939214/4563cfa6-8631-11e6-8e49-df2761fd02d7.png)

这张报表是用来查看数量的话，其实这些金额字段都不需要显示

**Comment by ie-it** [comment]
无法照顾到每一个人。

**Comment by GoodERPJeff** [comment]
暂不实现，需要和用户解释这里未考虑整单折扣
