### ISSUE TITLE
会计凭证 tree 视图，凭证明细列显示有问题

### ISSUE THREAD

**Issue by Judystudy** [osbzr/gooderp_addons#679]
操作系统及版本:
----
重现问题的步骤:
----
1.  新建会计凭证记录，查看 tree 视图
2.
3.
...

当前结果:
----

截图:
![Uploading image.png…]()

期望的结果:
----

**Comment by Judystudy** [comment]
![image](https://cloud.githubusercontent.com/assets/15152106/19225771/47e35fa2-8ed4-11e6-9b64-29ac4c4a858a.png)

**Comment by GoodERPJeff** [comment]
已解决
