### ISSUE TITLE
主菜单切换出BUG

### ISSUE THREAD

**Issue by luoguizhou** [osbzr/gooderp_addons#686]
## 重现问题的步骤:
1. 
   2.
   3.
   ...
## 当前结果:

http://localhost:8069/web/content/274-8d170e6/web.assets_backend.js:1619
回溯:
ViewManagerAction<.get_scrollTop@http://localhost:8069/web/content/274-8d170e6/web.assets_backend.js:1619:763
ActionManager<.start/<@http://localhost:8069/web/content/274-8d170e6/web.assets_backend.js:1619:2066
Events<.trigger@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:3098:166
EventDispatcherMixin<.trigger@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:3102:115
_notify@http://localhost:8069/web/content/274-8d170e6/web.assets_backend.js:1797:564
append@http://localhost:8069/web/content/274-8d170e6/web.assets_backend.js:1798:94
ActionManager<.push_action/<@http://localhost:8069/web/content/274-8d170e6/web.assets_backend.js:1626:1
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.when/updateFunc/<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:549:482
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.add@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:542:467
.Deferred/promise.then/</</<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:753
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.when/updateFunc/<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:549:482
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:31
ViewManager<.search/</<@http://localhost:8069/web/content/274-8d170e6/web.assets_backend.js:1704:90
.Deferred/promise.then/</</<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:678
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:31
ListView<.reload_content</</<@http://localhost:8069/web/content/274-8d170e6/web.assets_backend.js:2027:1
.Deferred/promise.then/</</<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:678
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.add@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:542:467
.Deferred/promise.then/</<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:631
.each@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:370:758
.Deferred/promise.then/<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:553
.Deferred@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:189
.Deferred/promise.then@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:518
ListView<.reload_content</<@http://localhost:8069/web/content/274-8d170e6/web.assets_backend.js:2026:1
ListView.Groups<.render/</<@http://localhost:8069/web/content/274-8d170e6/web.assets_backend.js:2083:633
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:31
DropMisordered<.add/<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:3217:259
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:546:198
done@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:937:86
.send/callback@http://localhost:8069/web/content/251-56bbc03/web.assets_common.js:957:15

截图:

**Comment by GoodERPJeff** [comment]
如何切换的，我这边没法重现，能否详细描述一下操作步骤？

**Comment by luoguizhou** [comment]
@GoodERPJeff  快速在上面菜单切换，在服务刚启动的时候概率很高

**Comment by luoguizhou** [comment]
@GoodERPJeff 最近没有出现了，关闭吧

**Comment by luoguizhou** [comment]
![dx v8 _x 1 c_ n z1](https://cloud.githubusercontent.com/assets/5688576/21283099/cc63e632-c437-11e6-9926-a398a719da30.png)

**Comment by luoguizhou** [comment]
![2kd abluhi o 2y31j_ nv](https://cloud.githubusercontent.com/assets/5688576/21283106/e22f5ca8-c437-11e6-9eaf-2ac31002518d.png)

**Comment by gilbert-yuan** [comment]
在线测试系统有类似的问题,估计是面包屑调用的一个方法的错误,出现的时机随机.
![default](https://cloud.githubusercontent.com/assets/13111533/21558576/44cc6cf4-ce77-11e6-9d98-be27c411ce85.png)
