### ISSUE TITLE
入库单生成的结算单应取入库日期

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#698]
## 重现问题的步骤:
1. 
   2.
   3.
   ...
## 当前结果:

![image](https://cloud.githubusercontent.com/assets/18207232/19264253/94a6feda-8fd2-11e6-912c-65a0034a2f91.png)
![image](https://cloud.githubusercontent.com/assets/18207232/19264273/a369379e-8fd2-11e6-8b6e-b30dca36917e.png)

截图:

**Comment by mrshelly** [comment]
图上两个日期不是一样的吗?
