### ISSUE TITLE
admin用户注销时提示错误

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#752]
操作系统及版本:
CentOS7，rpm包安装odoo10
重现问题的步骤:
点击注销
1. 
2.
3.
...

当前结果:
![qq 20161028105050](https://cloud.githubusercontent.com/assets/7471985/19795098/27a6aaba-9d0b-11e6-8c12-dccb13a18b3a.png)
----

截图:

期望的结果:
----

**Comment by GoodERPJeff** [comment]
是一处javascript的写法8和10不兼容
