### ISSUE TITLE
打印销货单出错

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#753]
操作系统及版本:
CentOS7 rpm包安装的Odoo10----
## 重现问题的步骤:
1. 
   2.
   3.
   ...
## 当前结果:

截图:
![qq 20161028123827](https://cloud.githubusercontent.com/assets/7471985/19795127/86d1a936-9d0b-11e6-9159-6898926b4e26.png)

**Comment by GoodERPJeff** [comment]
阿里云上问题已重现
