### ISSUE TITLE
销货单报表设为输出pdf时打印销售单出错

### ISSUE THREAD

**Issue by fenshuajiang** [osbzr/gooderp_addons#754]
操作系统及版本:
CentOS7.0 RPM包安装的Odoo10.0----
## 重现问题的步骤:
1. 
   2.
   3.
   ...
## 当前结果:

截图:
![56bxnkn gxlb9x86ol 3 v](https://cloud.githubusercontent.com/assets/7471985/19795230/7f161ce4-9d0c-11e6-815e-1d474ebf9ba5.png)

**Comment by GoodERPJeff** [comment]
怎么设置为输出pdf的？应该修改的是输出类型，而不是报表类型。

![image](https://cloud.githubusercontent.com/assets/1857069/19836389/6011b770-9eda-11e6-9b6a-3e9fc9615280.png)
