### ISSUE TITLE
组装单报错

### ISSUE THREAD

**Issue by sasakuma** [osbzr/gooderp_addons#818]
操作系统及版本:
----
重现问题的步骤:
----
1. 建立物料A，使用批次
2.建立物料B，使用属性，
3.建立物料C，C=A+B
4.创建组装单，配置子件，组合件数量为1，保存为模版。
5.依据组装单模版C，创建组装单，组合件数量修改为非1，添加A的批次规格，B的属性，
6.点击保存，  **显示 出库明细 报错**。
当前结果:
----

截图:

期望的结果:
----

**Comment by gilbert-yuan** [comment]
经测试 造成这个问题的应该是批次的问题 . 解决方案.
1. 如果组合产品c ,具有 批号管理 属性  请 勾选专家模式 在组合件中详细配置 (默认是简单模式 )
2. 如果 子件中产品 具有批号管理属性 且 每个产品一个批号.  修改组合件数量  能自动修改子件的数量(模板中只是简单的记录了子件和组合件的 数量比 ) 但是 这 样是不正确的.(因为要多行才能 记录 一个产品一个批号的行) 这种情况就只能手动的新建行 --点击复制会快点.
