### ISSUE TITLE
资金-外币

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#863]
操作系统及版本:
----
重现问题的步骤:
----
1.资金转账单

2.

3.

...

当前结果:
----
保存审核后，在反审核，在美金账户余额是人民币金额应是美金金额

截图:

![image](https://cloud.githubusercontent.com/assets/18207232/20662910/77abd6dc-b590-11e6-9857-14eeeb8f9c67.png)
![image](https://cloud.githubusercontent.com/assets/18207232/20662992/d3534a1a-b590-11e6-9992-12d73150ea74.png)

期望的结果:
----

**Comment by xuanyimin** [comment]
反审核是删除原来记帐凭证呀！

**Comment by lilnn** [comment]
是删除了，反回到原来账户的金额应该是美金吧（收外币的金额时也是在余额里，而不在外币金额里）
![image](https://cloud.githubusercontent.com/assets/18207232/20692913/e2c2002e-b615-11e6-86a7-6ba3fc677837.png)

**Comment by lilnn** [comment]
勾选“期末调汇”是在结账后生成调汇凭证吗？不勾选，是每笔自己输入调汇凭证。是这样用的吗？

**Comment by xuanyimin** [comment]
勾选则此科目需要期末调汇，不勾选则不调汇，手工自己调〜

**Comment by lilnn** [comment]
外币金额字段已删除
