### ISSUE TITLE
公司里需要邮箱field

### ISSUE THREAD

**Issue by Goya-** [osbzr/gooderp_addons#870]
当前结果:
----
无法设置公司邮箱，导致网站主页不能显示邮箱。

截图:
![2016-11-30_10-18-45](https://cloud.githubusercontent.com/assets/7187511/20737255/7cb684a4-b6e6-11e6-80f0-fd79a2f70d2e.png)

期望的结果:
----
可以设置公司邮箱，网站主页能显示公司邮箱。

**Comment by Judystudy** [comment]
这个 在 配置--高级配置--系统参数 里已经设置了。
![image](https://cloud.githubusercontent.com/assets/15152106/20737647/fb5d6e2e-b6e8-11e6-95b8-4cb428c052df.png)
