### ISSUE TITLE
输入的产品和属性不匹配时报错

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#873]
操作系统及版本:
----
重现问题的步骤:
----
1.新建发货单 

2.输入产品键盘，选择属性白

3.修改产品为鼠标，保存，审核

...

当前结果:
----
提示产品库存不足

截图:

期望的结果:
----

审核 wh_move时检查：

如产品不做属性管理，直接清空属性字段值。

如产品做属性管理，应查找同名属性值系统替换掉。

如无同名属性值，应报错，输入的产品xxx和属性不匹配，请重新选择属性。

**Comment by gilbert-yuan** [comment]
这本身就是个程序上的bug. 保存的时候就不应该把产品 不存在的 属性存进去

**Comment by lilnn** [comment]
已测试
