### ISSUE TITLE
【商品】中增加“备注”栏位

### ISSUE THREAD

**Issue by michaelchong2005** [osbzr/gooderp_addons#876]
操作系统及版本:
----All
重现问题的步骤:
----
1.【商品】资料查看

当前结果:
----
业务运作过程中，需要对商品做一些辅助说明备查，无栏位可录入。

截图:
![ga e68d9w 3 d45tz t982g](https://cloud.githubusercontent.com/assets/8684499/20855771/c86b7f1e-b93c-11e6-985a-31c7d5e14e80.jpg)

期望的结果:
----
增加“备注”栏位备用

**Comment by lilnn** [comment]
已测试
