### ISSUE TITLE
收支单审核报错，有错字

### ISSUE THREAD

**Issue by JasonAxesen** [osbzr/gooderp_addons#884]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/18279414/20962034/97aa9c0c-bca2-11e6-86fb-3416c3906323.png)

期望的结果:
----

**Comment by GoodERPJeff** [comment]
已经改过了
