### ISSUE TITLE
销售费用

### ISSUE THREAD

**Issue by lilnn** [osbzr/gooderp_addons#906]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----
![image](https://cloud.githubusercontent.com/assets/18207232/21087898/f075aac8-c064-11e6-839b-0bcb87674228.png)

**Comment by GoodERPJeff** [comment]
理解错误，这里的金额是不含税的
