### ISSUE TITLE
屏幕缩小 编辑状态的form 页面的tree 的行 超出列表

### ISSUE THREAD

**Issue by gilbert-yuan** [osbzr/gooderp_addons#916]
![2016-12-14 11 00 33](https://cloud.githubusercontent.com/assets/13111533/21168223/4c8d1be6-c1ed-11e6-845c-a932cd071f57.png)
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by gilbert-yuan** [comment]
![2016-12-14 13 50 44](https://cloud.githubusercontent.com/assets/13111533/21171051/61a99ace-c204-11e6-9551-92288a57b7ab.png)

**Comment by lilnn** [comment]
已测试
