### ISSUE TITLE
人力资源员工信息无法登陆系统

### ISSUE THREAD

**Issue by baishan2016** [osbzr/gooderp_addons#919]
操作系统及版本:
----
重现问题的步骤:
----
1.在登陆界面有 “手机号/邮箱/用户名”可选用，但是实际
人力资源中员工的角色信息无法绑定登陆，手机号、用户名方式无法登陆。

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by GoodERPJeff** [comment]
登陆界面有 “手机号/邮箱/用户名”

这里是指，在新建用户的时候，login字段推荐使用手机号，或者员工的工作邮箱，实在不行才使用用户名

并不是说用户可以根据对应员工的这些信息登录
