### ISSUE TITLE
采购入库单审核,不能通过

### ISSUE THREAD

**Issue by cncg51** [osbzr/gooderp_addons#920]
操作系统及版本:
----
重现问题的步骤:
----
1.采购入库单审核,不能通过
似是某个必填项没有填写,但视图中却没有显示

当前结果:
----

截图:

![image](https://cloud.githubusercontent.com/assets/3429563/21174697/a4351674-c219-11e6-82da-12d7c35c501d.png)

期望的结果:
----

**Comment by GoodERPJeff** [comment]
看一下 配置-基本配置-类别 菜单

除了属性，其他类别都应该有指定的科目
