### ISSUE TITLE
委外加工单 outsource

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#924]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----
抽象为，特殊的组装单

上面有委外供应商，关联的组装单，委外费用金额

委外完成审核此单，生成结算单，减少委外材料，增加成品数量

**Comment by lilnn** [comment]
要把加工费用分配到组合件上
