### ISSUE TITLE
新建供应商界面纳税人认别号。

### ISSUE THREAD

**Issue by baishan2016** [osbzr/gooderp_addons#930]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----供应商的界面的纳税人认别号最好能增加一项。

**Comment by GoodERPJeff** [comment]
一般我们如果需要给客户开专用发票，需要客户的税号。
但是供应商的税号我们在什么场景下使用呢？

**Comment by baishan2016** [comment]
有时既是客户又是供应商的情况下 ，那是否要在客户与供应商各输一次的客户信息的？核对发票时会不会用到的。

**Comment by GoodERPJeff** [comment]
可以在客户界面上增加税号字段，非必输
