### ISSUE TITLE
首页标题显示错误 

### ISSUE THREAD

**Issue by luoguizhou** [osbzr/gooderp_addons#939]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----
![j 6t_s45vv rymk2x35 42](https://cloud.githubusercontent.com/assets/5688576/21251877/bb8ea546-c38c-11e6-9741-69841eb9f306.png)

截图:

期望的结果:
----

**Comment by gilbert-yuan** [comment]
最新代码没有重现(这里面进行过数据的重新设置).数据的更新导致的这么乱, 你可以尝试把这里面的设置项删除  升级一下模块.
