### ISSUE TITLE
隐藏Odoo自带的组

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#945]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----
人力资源和销售两个组是odoo自带的，显示在用户界面上会造成难以理解或误操作

截图:

期望的结果:
----
将这两个组放入no_one组，使得其只在开发者模式出现。

**Comment by gilbert-yuan** [comment]
i will do it
