### ISSUE TITLE
新建数据库，加载测试数据，无法知道产品的当前库存

### ISSUE THREAD

**Issue by gagaboy** [osbzr/gooderp_addons#952]
操作系统及版本:
----
重现问题的步骤:
----
1.
新建数据库，加载测试数据
2.
进入仓库->报表 ->库存余额表，内容为空
不显示当前测试数据的当前库存数
3.

...

当前结果:
----

截图:

期望的结果:
----
产品form信息中加两个tree，显示该产品的采购信息（采购单号，采购数，已入库数）和销售信息（销货单号，销货数和已出库数）

**Comment by GoodERPJeff** [comment]
测试数据的库存相关单据都是未审核状态，所以商品的库存余额全是0. 审核一张其它入库单看看
