### ISSUE TITLE
Bug，入库单，通过明细行“添加项目”操作，输入商品，没有带出单价填充到“入库单价”列（扫描输入可以）

### ISSUE THREAD

**Issue by ie-it** [osbzr/gooderp_addons#958]
操作系统及版本:
----
重现问题的步骤:
----
1.其他入库单，创建

2.通过明细行“添加项目”操作，输入商品，换到输入数量...

3.没有带出单价填充到“入库单价”列（扫描输入可以），审核会提示借、贷不能都为0

...

当前结果:
----

截图:

期望的结果:
----
带出单价填充到“入库单价”列（扫描输入可以）

**Comment by gilbert-yuan** [comment]
其实扫描的时候也不应该带出入库单间,入库单价是浮动的,并不固定.(扫描带出的是产品的成本价)

**Comment by ie-it** [comment]
如果用户只用简单进销存，并不关心钱，只关心数据，那“借、贷不能都为0”就硬卡住用户了，当基础数据中有时，带出来，可以省事，也不提示卡住用户，用户是否修改基础单价，再由用户决定是合理的。

**Comment by GoodERPJeff** [comment]
谢谢 @ie-it

确实这里设计得有些理想化。自动生成凭证本身是对的，不管客户现在看不看，我们还是有办法让他们逐步正规化管理的，那个时点开始之前我们生成的数据可以作为鼓励他们关注财务数字的一个起点。

从仓库单据生成会计凭证的时候，有些单据行有可能是金额为0的，对于这样的行应该忽略掉，不创建会计凭证行，而不应该报错，可能的场景有：

* 客户不管理成本，只关注数量，则所有商品和单据的成本字段都为0
* 收发货的时候包含赠品，客户手动在订单或收发货单上将单价改为0

**Comment by Judystudy** [comment]
好的，我来改。

**Comment by GoodERPJeff** [comment]
其它入库单已支持0价格的行
