### ISSUE TITLE
物料清单需添加 属性 字段

### ISSUE THREAD

**Issue by honwe** [osbzr/gooderp_addons#959]
操作系统及版本:
----
重现问题的步骤:
----
1.物料清单需添加 属性 字段

2.

3.

...

当前结果:
组装单选择模板后子件属性需手动选择

截图:
![qq 20161221170036](https://cloud.githubusercontent.com/assets/24694142/21383172/536c7e22-c79f-11e6-8b31-93c8becffdcf.png)

期望的结果:
组装单选择模板可以带出子件属性

**Comment by lilnn** [comment]
已测试
