### ISSUE TITLE
委外加工单

### ISSUE THREAD

**Issue by xuanyimin** [osbzr/gooderp_addons#961]
根据Jeff所说重视过程：
那么加工单本身是一个合同，希望如下：
1.生成领料出库单（最好是新的模版）
2.生成成品入库单（同上）
3.生成服务采购单
以对应三个不同的过程节点
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by lilnn** [comment]
1和2已实现
