### ISSUE TITLE
用Safari访问产品列表，看不到全部产品

### ISSUE THREAD

**Issue by luoguizhou** [osbzr/gooderp_addons#962]
操作系统及版本:
----
重现问题的步骤:
----
1.用手机Safari打开产品列表

2.产品信息条目大于屏幕大小

3.

...

当前结果:
----
上下滑屏，不能看到下面的记录

截图:

期望的结果:
----

**Comment by luoguizhou** [comment]
![diamond_list](https://cloud.githubusercontent.com/assets/5688576/21418081/cdd04b3e-c859-11e6-96c0-73967f497de6.png)

**Comment by gilbert-yuan** [comment]
手机上问题还很多=-=,有待修复.

**Comment by gilbert-yuan** [comment]
在手机端google浏览器,和firefox 支持比较好,其他的没测试.

**Comment by luoguizhou** [comment]
@gilbert-yuan  一样有问题 firefox 手机端

**Comment by gilbert-yuan** [comment]
试试android下的呗.iPhone下没试过..

**Comment by luoguizhou** [comment]
@gilbert-yuan android上面可以，iPhone下不行

**Comment by luoguizhou** [comment]
iPhone + Firefox/Chrome/Safari 显示不正常
Android + Firefox/Chrome 显示正常

**Comment by GoodERPJeff** [comment]
在网上找了个方案，请试一下

**Comment by leangjia** [comment]
求iphone以测试 :)))

**Comment by GoodERPJeff** [comment]
https://github.com/osbzr/gooderp_addons/commit/9b4589c402d6f0d0bd5ef207c14a43c9daea644a
