### ISSUE TITLE
gooderp 绿色版右上角图表，从 odoo 换成 gooderp

### ISSUE THREAD

**Issue by Judystudy** [osbzr/gooderp_addons#970]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/15152106/21449289/bfa6fd6e-c926-11e6-9031-76ecb395c2c1.png)

期望的结果:
----
![image](https://cloud.githubusercontent.com/assets/15152106/21449305/e8656060-c926-11e6-9e13-5efbea2e46de.png)

**Comment by GoodERPJeff** [comment]
这个是nologo的时候自动加上去的，yuan是不是改过？

**Comment by lilnn** [comment]
已改
