### ISSUE TITLE
创建属性值界面应该自动将属性填充上，在收支项界面创建其他收入类时应自动填充上类型

### ISSUE THREAD

**Issue by floraXiao** [osbzr/gooderp_addons#971]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/13793204/21450740/72a7e722-c934-11e6-8fea-bc53abd4ca8c.png)

期望的结果:
----

**Comment by floraXiao** [comment]
已修改

**Comment by lilnn** [comment]
已测试
