### ISSUE TITLE
商机管理没有默认阶段..

### ISSUE THREAD

**Issue by gilbert-yuan** [osbzr/gooderp_addons#972]
![2016-12-23 16 33 47](https://cloud.githubusercontent.com/assets/13111533/21451055/0713e224-c937-11e6-901c-a518c07e2f7c.png)
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by lilnn** [comment]
已测试
