### ISSUE TITLE
人事部门的bug...

### ISSUE THREAD

**Issue by gilbert-yuan** [osbzr/gooderp_addons#973]
1.上级部门可以选自己 
2.职位只能查看不能直接添加比较麻烦..
![2016-12-23 16 30 45](https://cloud.githubusercontent.com/assets/13111533/21451085/48c82e32-c937-11e6-9f15-049effa000e0.png)
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----

截图:

期望的结果:
----

**Comment by lilnn** [comment]
已测试
