### ISSUE TITLE
其他出库单及移库单明细行中选批号时只应该过滤出单子上调出仓库的批号

### ISSUE THREAD

**Issue by floraXiao** [osbzr/gooderp_addons#974]
操作系统及版本:
----
重现问题的步骤:
----
1.
新建其他出库单，选择一个调出仓
2.
明细行中选择有批号产品，在批号下拉框中，可以看到其他仓库的产品。
3.

...

当前结果:
----

截图:
![image](https://cloud.githubusercontent.com/assets/13793204/21451393/d9867008-c939-11e6-8fbc-fcb608776c55.png)

期望的结果:
----
批号下拉出来只显示调出仓库的批号

**Comment by luoguizhou** [comment]
good

**Comment by floraXiao** [comment]
已修改

**Comment by lilnn** [comment]
已测试
