### ISSUE TITLE
新建任务时界面上没有任务阶段进度条

### ISSUE THREAD

**Issue by floraXiao** [osbzr/gooderp_addons#985]
操作系统及版本:
----
重现问题的步骤:
----
1.
任务菜单，新建一个任务
2.

3.

...

当前结果:
----
右上角没有出现任务阶段进度条，没法修改任务阶段

截图:

期望的结果:
----
显示任务阶段进度条，可以点击进行修改

**Comment by lilnn** [comment]
已测试
