### ISSUE TITLE
商品上增加 不可销售 boolean字段

### ISSUE THREAD

**Issue by GoodERPJeff** [osbzr/gooderp_addons#992]
操作系统及版本:
----
重现问题的步骤:
----
1.

2.

3.

...

当前结果:
----
销售订单和发货单可以选到所有商品

截图:

期望的结果:
----
部分商品可以标识为 不可销售，这样销售订单和发货单上加个过滤就选不到这样的产品

**Comment by Judystudy** [comment]
我来做
